export type PetDestinationTierValue = "NEARBY" | "CHINA" | "WORLD";

export type PetDestinationScene =
  | "ancient-town"
  | "city"
  | "desert"
  | "forest"
  | "garden"
  | "grassland"
  | "ice"
  | "island"
  | "lake"
  | "mountain"
  | "museum"
  | "ocean"
  | "palace"
  | "science"
  | "temple"
  | "tower"
  | "waterfall"
  | "wildlife";

type DestinationDraft = {
  slug: string;
  name: string;
  city: string;
  country: string;
  tier: PetDestinationTierValue;
  story: string;
  explore: string;
  funFact: string;
  scene: PetDestinationScene;
};

const nearbyDestinations: DestinationDraft[] = [
  {
    slug: "chengdu-peoples-park",
    name: "成都人民公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "人民公园里有湖水、老树、茶馆和热闹的小广场，是成都人休息聊天的城市客厅。清晨能听见鸟叫，午后常有人喝茶、下棋和练习川剧清音。",
    explore: "跟着星宠散步时，可以找一找不同形状的茶壶，观察公园里的人怎样享受慢悠悠的一天。",
    funFact: "公园里的鹤鸣茶社已有一百多年历史，竹椅和盖碗茶是很有成都味道的风景。",
    scene: "garden",
  },
  {
    slug: "eastern-suburb-memory",
    name: "东郊记忆",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "东郊记忆由旧工厂改造而来，高高的烟囱、红砖厂房和老机器旁边，如今有音乐舞台、展览和创意小店。过去与现在在这里并排出现。",
    explore: "可以和星宠比较老厂房与新建筑的不同，猜一猜留下来的管道和齿轮原来负责什么工作。",
    funFact: "这里曾是生产电子设备的工厂，改造时特意保留了许多工业建筑和机器零件。",
    scene: "city",
  },
  {
    slug: "tianfu-art-park",
    name: "天府艺术公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "天府艺术公园把湖泊、草地、花园和美术馆连在一起，建筑倒映在水中，像一幅可以走进去的画。不同季节的植物会给公园换上新的颜色。",
    explore: "参观时可以挑一座最喜欢的建筑，从远处和近处各看一次，发现线条、影子和倒影怎样组合。",
    funFact: "园区里的天府美术馆外形像一朵盛开的芙蓉花，成都也常被称为蓉城。",
    scene: "museum",
  },
  {
    slug: "chengdu-open-air-music-park",
    name: "成都露天音乐公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "这是一座能在草地和天空下听音乐的公园，巨大的舞台像一只展开翅膀的凤凰。河流、步道和开阔草坪让声音与自然待在一起。",
    explore: "跟着星宠站在不同位置拍拍手，听一听声音远近有什么变化，再找找舞台上的对称图形。",
    funFact: "主舞台使用了特殊的声学设计，让大型演出不需要封闭屋顶也能把音乐送向观众。",
    scene: "garden",
  },
  {
    slug: "chengdu-botanical-garden",
    name: "成都植物园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "成都植物园收集了许多不同地区的树木、花卉和药用植物，温室里还能看到喜欢温暖环境的植物。沿着小路走，就像翻阅一本有香气的植物图鉴。",
    explore: "可以观察叶子的大小、边缘和纹路，选三片形状不同的叶子，用眼睛完成一次不采摘的分类游戏。",
    funFact: "植物学家会制作植物标本，把叶、花和果实的信息保存下来，帮助以后的人继续研究。",
    scene: "forest",
  },
  {
    slug: "chengdu-zoo",
    name: "成都动物园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "成都动物园里生活着大熊猫、金丝猴、长颈鹿和许多鸟类。每种动物都有适合自己的食物、活动空间和休息方式，饲养员每天认真照顾它们。",
    explore: "参观时可以比较动物的脚、嘴巴和尾巴，想一想这些身体特点怎样帮助它们寻找食物和保护自己。",
    funFact: "长颈鹿的脖子很长，但它和人一样通常只有七块颈椎，只是每一块都长得多。",
    scene: "wildlife",
  },
  {
    slug: "chengdu-polar-ocean-park",
    name: "成都极地海洋公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "在远离海边的成都，也能通过水族展馆认识企鹅、海豹、海龟和多彩的鱼。蓝色水池模拟了不同海洋环境，让人看到水下生命怎样游动和呼吸。",
    explore: "跟着星宠观察三种动物的游泳姿势，比较鳍、尾巴和身体形状，再想想谁最适合快速前进。",
    funFact: "企鹅虽然不会飞，却把翅膀变成了有力的鳍，在水里游动时像在海中飞翔。",
    scene: "ocean",
  },
  {
    slug: "west-china-medical-campus",
    name: "华西坝钟楼",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "华西坝的老建筑、钟楼和林荫道记录着成都近代教育与医学的发展。红砖墙、坡屋顶和宽阔草地，让校园既安静又有历史感。",
    explore: "可以抬头观察钟面的数字与指针，听钟声经过多久再次响起，再比较老建筑和新建筑的窗户。",
    funFact: "华西坝的校园建筑把中国传统屋顶和西式红砖结构结合在一起，形成了很特别的样子。",
    scene: "tower",
  },
  {
    slug: "wangjiang-pavilion-park",
    name: "望江楼公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "望江楼公园靠近锦江，园内有古塔、竹林和纪念唐代女诗人薛涛的建筑。风吹过竹叶时沙沙作响，江水与古楼一起组成安静的诗意风景。",
    explore: "跟着星宠数一数竹子有多少种绿色，找找塔楼每一层重复出现的屋檐和窗格。",
    funFact: "薛涛喜欢用浣花溪水制作小巧的彩色诗笺，后来人们把这种纸叫作薛涛笺。",
    scene: "tower",
  },
  {
    slug: "jinli-ancient-street",
    name: "锦里古街",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "锦里古街有木楼、灯笼、戏台和许多四川传统小吃，石板路把一个个小院连接起来。傍晚灯光亮起时，整条街像一本热闹的三国故事书。",
    explore: "可以寻找门窗上的花纹、招牌上的汉字和不同形状的灯笼，选一个最喜欢的图案记在心里。",
    funFact: "“锦里”这个名字和古代织锦有关，成都的蜀锦曾经非常有名，还专门设置过管理织锦的官员。",
    scene: "ancient-town",
  },
  {
    slug: "qingyang-palace",
    name: "青羊宫",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "青羊宫是一组藏在大树之间的古建筑，院落里有殿堂、石刻和形态特别的铜羊。这里能看到传统建筑讲究的中轴、对称和层层院门。",
    explore: "参观时可以站在院子中间观察左右两边，找出成对出现的门、树和石兽，再看看屋脊上的装饰。",
    funFact: "三清殿前的铜羊看起来像羊，却集合了鼠、牛、虎等多种动物的身体特征。",
    scene: "temple",
  },
  {
    slug: "wenshu-monastery",
    name: "文殊院",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "文殊院由一进进安静的院落组成，红墙、古树和木结构殿堂让城市的声音慢下来。附近的街巷还保留着茶馆、书店和传统点心。",
    explore: "可以轻声走过石板路，观察屋檐为什么向上翘，再找找木门上重复排列的方格和圆形。",
    funFact: "院内保存着许多书画和碑刻，古人会把重要文字刻在石头上，让它们保存更久。",
    scene: "temple",
  },
  {
    slug: "huanhuaxi-park",
    name: "浣花溪公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "浣花溪公园有溪流、湿地、树林和诗歌小路，与杜甫草堂相邻。水鸟在浅水边寻找食物，诗句刻在路旁，让自然观察和文学相遇。",
    explore: "跟着星宠沿溪寻找倒影、涟漪和水边植物，挑一句看得懂的诗，再用自己的话说说画面。",
    funFact: "“浣花”有洗花的意思，关于这个名字流传着许多美丽故事，溪水也因此带上了诗意。",
    scene: "garden",
  },
  {
    slug: "guixi-ecological-park",
    name: "桂溪生态公园",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "桂溪生态公园像一块铺在城市里的绿色地毯，草坪、湖泊、树林和骑行道连接成开阔空间。雨水会被花园和湿地慢慢收集，帮助城市更好地呼吸。",
    explore: "可以观察水从高处流向低处的路线，找找哪些植物生长在干燥地面，哪些更喜欢靠近水边。",
    funFact: "生态公园里的下凹绿地像天然海绵，下雨时能暂时存水，减少道路一下子积满雨水。",
    scene: "garden",
  },
  {
    slug: "tianfu-panda-tower",
    name: "天府熊猫塔",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "天府熊猫塔是一座高高的广播电视塔，细长塔身和圆形观景层从很远就能看到。登上高处，城市道路、河流和楼房会变成地图一样的图案。",
    explore: "可以从塔下抬头观察它由哪些几何形状组成，再到地图上找找电视塔在成都的哪个方向。",
    funFact: "电视塔不仅是观景建筑，还承担广播和电视信号传输工作，把节目送到许多家庭。",
    scene: "tower",
  },
  {
    slug: "longquanyi-peach-blossom-village",
    name: "桃花故里",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "春天的龙泉山坡会开满粉色桃花，果园、村庄和远处城市层层展开。花谢之后，小小果实慢慢长大，夏天便能闻到成熟桃子的香味。",
    explore: "跟着星宠观察花朵有几片花瓣，找一找蜜蜂怎样在花间工作，并记住只看不折花的旅行约定。",
    funFact: "桃花需要昆虫帮助传粉，花粉从一朵花来到另一朵花后，才更有机会结出果实。",
    scene: "garden",
  },
  {
    slug: "xinjin-baihetan-wetland",
    name: "新津白鹤滩湿地",
    city: "成都",
    country: "中国",
    tier: "NEARBY",
    story: "白鹤滩湿地有河流、浅滩、芦苇和大片水边植物，是候鸟休息与寻找食物的地方。季节变化时，来到这里的鸟类也会跟着改变。",
    explore: "可以带着望远镜安静观察鸟的嘴、腿和飞行姿势，猜猜它更喜欢捉鱼、吃种子还是在泥里找小虫。",
    funFact: "湿地既是动物的家，也像天然净水器，植物根系和泥土能帮助过滤一部分水中杂质。",
    scene: "lake",
  },
  {
    slug: "qionglai-tiantaishan",
    name: "邛崃天台山",
    city: "邛崃",
    country: "中国",
    tier: "NEARBY",
    story: "天台山森林茂密，山间有溪流、瀑布和被水冲刷得圆润的石头。夏夜还能遇见萤火虫，微小亮光在黑暗中一闪一闪。",
    explore: "白天可以听水声寻找溪流方向，夜晚如果观察萤火虫，要关掉强光、保持距离，不打扰它们。",
    funFact: "萤火虫发光是一种生物发光，身体里的物质发生反应时能产生冷光，几乎不会发热。",
    scene: "forest",
  },
  {
    slug: "western-sichuan-bamboo-sea",
    name: "川西竹海",
    city: "邛崃",
    country: "中国",
    tier: "NEARBY",
    story: "川西竹海的山谷里长着大片翠竹，竹林栈道和吊桥穿过绿色海洋。风吹来时，竹叶像波浪一样起伏，空气里有清新的植物气味。",
    explore: "可以比较新竹与老竹的颜色和粗细，听脚步声在竹林里怎样变化，再数数竹节之间的距离。",
    funFact: "竹子属于禾本科植物，有些种类生长速度很快，但一生通常只在特别的年份开花。",
    scene: "forest",
  },
  {
    slug: "jianchuan-museum-cluster",
    name: "建川博物馆聚落",
    city: "大邑",
    country: "中国",
    tier: "NEARBY",
    story: "建川博物馆聚落由许多主题不同的展馆组成，收藏了老照片、生活用品、书信和历史物件。普通人的衣食住行也能成为认识时代的重要线索。",
    explore: "跟着星宠挑一件看得懂的老物件，猜它怎么使用，再和今天家里的同类物品比较哪里变方便了。",
    funFact: "博物馆不只收藏珍贵宝物，一张车票、一只水壶也能记录真实生活和社会变化。",
    scene: "museum",
  },
  {
    slug: "jiezi-ancient-town",
    name: "街子古镇",
    city: "崇州",
    country: "中国",
    tier: "NEARBY",
    story: "街子古镇靠近青城山，石板街、木屋、古塔和清澈河水组成悠闲的小镇风景。老街两旁能看到竹编、木工和传统点心。",
    explore: "可以沿着水渠观察水往哪里流，找找木房子的榫卯连接，再选择一种手艺认真看看制作步骤。",
    funFact: "古镇附近的味江河给居民带来水源，过去人们也会利用水流带动简单的生产工具。",
    scene: "ancient-town",
  },
  {
    slug: "fengqi-mountain",
    name: "凤栖山",
    city: "崇州",
    country: "中国",
    tier: "NEARBY",
    story: "凤栖山的森林步道在杉树和竹林间向上延伸，潮湿空气让苔藓铺在石头和树根旁。山里声音不多，更容易听见风、鸟和自己的脚步。",
    explore: "跟着星宠慢慢走，寻找向阳和背阴位置的植物差别，并用落在地上的叶子比较不同树种。",
    funFact: "苔藓没有真正的根，会直接从周围吸收水分，所以常出现在湿润、光线柔和的地方。",
    scene: "forest",
  },
  {
    slug: "pengzhou-danjing-mountain",
    name: "彭州丹景山",
    city: "彭州",
    country: "中国",
    tier: "NEARBY",
    story: "丹景山春天以牡丹闻名，大朵花朵在山坡和庭院中开放，颜色从白、粉到深红都有。山路还连接着古迹与观景台。",
    explore: "可以比较牡丹花瓣由里到外的排列，找找昆虫停在哪些花上，并观察山脚与高处开花时间是否相同。",
    funFact: "牡丹的花芽要经历冬天的低温，来年春天才更容易顺利生长并开出花朵。",
    scene: "garden",
  },
  {
    slug: "bailu-music-town",
    name: "白鹿音乐小镇",
    city: "彭州",
    country: "中国",
    tier: "NEARBY",
    story: "白鹿小镇坐在山谷里，彩色房屋、教堂式建筑和音乐空间让街道像童话舞台。远处青山和近处小河给小镇加上自然背景。",
    explore: "跟着星宠寻找不同颜色的窗户和屋顶，听一段音乐后画出声音让你想到的线条和形状。",
    funFact: "白鹿镇在地震后重建时保留了历史建筑特点，也加入了音乐教育和文化活动。",
    scene: "ancient-town",
  },
  {
    slug: "dujiangyan-panda-valley",
    name: "都江堰熊猫谷",
    city: "都江堰",
    country: "中国",
    tier: "NEARBY",
    story: "熊猫谷靠近森林和山地，为大熊猫提供了接近自然的生活空间。这里也开展野化训练和保护研究，帮助部分熊猫学习在更自然的环境中活动。",
    explore: "参观时要保持安静，观察熊猫怎样抓竹子、选择嫩叶和爬上木架，再找找它休息时喜欢的姿势。",
    funFact: "大熊猫的前爪有一块加大的腕骨，像“第六根手指”，能帮助它牢牢握住竹子。",
    scene: "wildlife",
  },
  {
    slug: "qingcheng-back-mountain",
    name: "青城后山",
    city: "都江堰",
    country: "中国",
    tier: "NEARBY",
    story: "青城后山有幽深树林、溪沟、瀑布和贴着山壁修建的栈道，比前山更像一条自然探险路线。水汽让岩石和植物一直保持湿润。",
    explore: "可以沿途比较瀑布上方与下方的水声，注意脚下防滑，并寻找岩壁上适应潮湿环境的小植物。",
    funFact: "山谷两边的岩壁会反射声音，所以水声有时听起来比实际距离更近、更响。",
    scene: "waterfall",
  },
  {
    slug: "wufengxi-ancient-town",
    name: "五凤溪古镇",
    city: "金堂",
    country: "中国",
    tier: "NEARBY",
    story: "五凤溪依山傍水，街道顺着坡地一层层展开，木屋、石梯和会馆记录着过去码头贸易的热闹。沱江水把这里与更远的地方连接起来。",
    explore: "跟着星宠数一数老街有多少级台阶，观察房屋怎样适应斜坡，再想象货物从码头运上街的路线。",
    funFact: "古镇名字来自周围五座像凤凰一样起伏的山峰，过去这里还是沱江边的重要水运码头。",
    scene: "ancient-town",
  },
  {
    slug: "mingyue-village",
    name: "明月村",
    city: "蒲江",
    country: "中国",
    tier: "NEARBY",
    story: "明月村有茶园、竹林、陶艺工作室和安静的乡村小路，传统农业与新的手工创作在这里相遇。泥土经过揉捏、拉坯和烧制，能变成坚硬器皿。",
    explore: "可以观察陶土从软到硬的变化，尝试用手捏出简单形状，再看看茶树整齐排列成怎样的线条。",
    funFact: "陶器要在高温窑炉里烧制，泥土中的成分发生变化后，才会变得结实并且不容易溶于水。",
    scene: "garden",
  },
  {
    slug: "sancha-lake",
    name: "三岔湖",
    city: "简阳",
    country: "中国",
    tier: "NEARBY",
    story: "三岔湖拥有许多岛屿和弯弯曲曲的湖岸，从高处看像一棵伸展开的蓝色大树。湖边的浅水、芦苇和树林为鸟类提供食物与藏身处。",
    explore: "跟着星宠观察远近岛屿大小为什么不同，在地图上用手指沿湖岸走一圈，感受它复杂的形状。",
    funFact: "三岔湖是一座人工湖，除了风景和生态作用，也承担储水等重要任务。",
    scene: "lake",
  },
  {
    slug: "sansuci-memorial",
    name: "眉山三苏祠",
    city: "眉山",
    country: "中国",
    tier: "NEARBY",
    story: "三苏祠纪念苏洵、苏轼和苏辙父子，庭院里有古树、池塘、亭台和关于他们生活与写作的展览。这里像一座安静的文学花园。",
    explore: "可以找一首苏轼写月亮、雨或食物的诗，观察院子里的景物，再试着说出一句自己的小诗。",
    funFact: "苏轼不只是文学家，也关心水利和百姓生活，杭州苏堤就与他治理西湖有关。",
    scene: "garden",
  },
  {
    slug: "wawu-mountain",
    name: "瓦屋山",
    city: "眉山",
    country: "中国",
    tier: "NEARBY",
    story: "瓦屋山山顶宽阔平坦，远看像一张巨大的桌子，森林、云海和瀑布分布在山体周围。冬季积雪会把树木和步道变成银白色。",
    explore: "跟着星宠比较山脚与山顶的温度和植物，观察云从山谷升起时怎样遮住又露出远处景物。",
    funFact: "瓦屋山属于桌山地貌，坚硬岩层像屋顶一样覆盖在上方，使山顶显得宽而平。",
    scene: "mountain",
  },
  {
    slug: "heilongtan-reservoir",
    name: "黑龙滩",
    city: "眉山",
    country: "中国",
    tier: "NEARBY",
    story: "黑龙滩是一片被群山和岛屿环绕的水域，湖湾很多，水面会随天空颜色变化。水库为周边地区提供水，也形成了新的湿地环境。",
    explore: "可以观察风吹过水面形成的波纹，比较背风处和迎风处的不同，再想想怎样一起保护饮用水源。",
    funFact: "水库像一个巨大的储水罐，会在雨水多时存水，并在需要时把水送往农田和城市。",
    scene: "lake",
  },
  {
    slug: "jiayang-steam-train",
    name: "嘉阳小火车",
    city: "乐山",
    country: "中国",
    tier: "NEARBY",
    story: "嘉阳小火车沿着窄窄铁轨穿过山坡、村庄和油菜花田，蒸汽机车会吐出白色水汽并发出响亮汽笛。它保留了早期工业交通的模样。",
    explore: "跟着星宠数车轮、车厢和隧道，听汽笛远近变化，并观察铁轨为什么总是保持两条平行线。",
    funFact: "蒸汽机车把水加热成蒸汽，利用蒸汽推动活塞，再带动车轮向前转动。",
    scene: "science",
  },
  {
    slug: "emeishan-museum",
    name: "峨眉山博物馆",
    city: "乐山",
    country: "中国",
    tier: "NEARBY",
    story: "峨眉山博物馆把山里的岩石、植物、动物和历史文化集中展示，让登山前的人先读懂这座山。标本和模型能看到平时不容易靠近的自然细节。",
    explore: "可以先在展厅找出最想见的动物或植物，再到户外保持距离寻找它生活环境留下的线索。",
    funFact: "峨眉山从山脚到山顶高度差很大，因此同一座山上能分布许多不同气候带的生物。",
    scene: "museum",
  },
  {
    slug: "mianzhu-new-year-picture-village",
    name: "绵竹年画村",
    city: "德阳",
    country: "中国",
    tier: "NEARBY",
    story: "绵竹年画村把鲜艳年画画在门板、墙面和纸张上，人物表情夸张又喜庆。画师会经过勾线、刻版、印墨和彩绘等步骤完成作品。",
    explore: "跟着星宠找出画面里的对称、重复和吉祥图案，选择两种最明亮的颜色设计自己的小门神。",
    funFact: "绵竹年画与天津杨柳青、苏州桃花坞等年画一起，是中国著名的民间年画传统。",
    scene: "ancient-town",
  },
  {
    slug: "deyang-confucian-temple",
    name: "德阳文庙",
    city: "德阳",
    country: "中国",
    tier: "NEARBY",
    story: "德阳文庙有红墙、棂星门、泮池和层层殿宇，是古代人尊师重教、举行礼仪活动的地方。建筑排列整齐，屋顶装饰十分精细。",
    explore: "可以从入口沿中轴线慢慢走，寻找左右对称的建筑和石栏，再观察门上的木雕讲了什么故事。",
    funFact: "古代文庙前常有半圆形水池叫泮池，学生入学也被称为“入泮”。",
    scene: "temple",
  },
  {
    slug: "mianyang-science-technology-museum",
    name: "绵阳科技馆",
    city: "绵阳",
    country: "中国",
    tier: "NEARBY",
    story: "绵阳科技馆展示航空、航天、核科技和信息技术，用模型与互动装置讲解看不见的科学力量。火箭怎样升空、卫星怎样工作，都能找到直观线索。",
    explore: "跟着星宠挑一个装置先猜结果，再动手验证，把猜想和实际现象不同的地方认真记住。",
    funFact: "火箭向后高速喷出气体时，会得到一个向前的反作用力，这个力量把它推向天空。",
    scene: "science",
  },
  {
    slug: "beichuan-qiang-town",
    name: "北川羌城",
    city: "绵阳",
    country: "中国",
    tier: "NEARBY",
    story: "北川羌城展示羌族碉楼、歌舞、刺绣和山地生活，也保存着关于地震记忆与灾后重建的教育内容。这里讲述了人与家园互相守护的故事。",
    explore: "可以观察羌族建筑怎样使用石头，找找刺绣里的羊角和花草图案，并学习遇到地震时保护自己的方法。",
    funFact: "羌族传统碉楼用石块层层砌成，不需要现代水泥也能建得很高，体现了古老建筑智慧。",
    scene: "ancient-town",
  },
  {
    slug: "jiangyou-li-bai-memorial",
    name: "李白纪念馆",
    city: "江油",
    country: "中国",
    tier: "NEARBY",
    story: "江油是诗人李白成长的地方，纪念馆用庭院、书画和诗歌介绍他充满想象力的一生。山水、月亮和远行经常出现在他的诗句里。",
    explore: "跟着星宠找一句熟悉的李白诗，看看展览里的山水画，再把诗句想象成一幅自己的画面。",
    funFact: "李白一生去过许多地方，他把旅途中看见的江河、瀑布和月色写进了大量诗歌。",
    scene: "garden",
  },
  {
    slug: "bifengxia-gorge",
    name: "雅安碧峰峡",
    city: "雅安",
    country: "中国",
    tier: "NEARBY",
    story: "碧峰峡两侧山崖被森林覆盖，溪水和瀑布在峡谷底部穿行。这里雨水充沛、空气湿润，也是许多动植物生活的绿色走廊。",
    explore: "可以听声音判断瀑布方向，比较峡谷内外的温度与湿度，并在安全步道上寻找水滴留下的痕迹。",
    funFact: "峡谷通常由流水长时间侵蚀岩石形成，水量、岩性和时间共同决定它的深浅与形状。",
    scene: "waterfall",
  },
  {
    slug: "mengding-mountain",
    name: "蒙顶山",
    city: "雅安",
    country: "中国",
    tier: "NEARBY",
    story: "蒙顶山常被云雾包围，湿润气候和缓坡很适合茶树生长。茶园像整齐的绿色波纹铺在山腰，人们在春天采下嫩芽制作茶叶。",
    explore: "跟着星宠观察茶叶边缘和叶脉，比较新芽与老叶的颜色，再看看茶农怎样只采合适的部分。",
    funFact: "茶叶经过杀青、揉捻和干燥等步骤，水分与香气会发生变化，才成为可以保存的成品茶。",
    scene: "mountain",
  },
  {
    slug: "yaan-bifengxia-panda-base",
    name: "雅安大熊猫基地",
    city: "雅安",
    country: "中国",
    tier: "NEARBY",
    story: "雅安山地湿润、竹林丰富，是大熊猫重要的家园之一。基地里的熊猫在坡地、树木和水池组成的环境中活动，也接受健康检查与保护研究。",
    explore: "参观时可以记录一只熊猫十分钟里做了什么，看看它花多少时间吃竹子、爬树、走路或休息。",
    funFact: "大熊猫每天要花很长时间进食，因为竹子的能量不高，需要吃下较多才能满足身体需要。",
    scene: "wildlife",
  },
  {
    slug: "anyue-stone-carvings",
    name: "安岳石刻",
    city: "资阳",
    country: "中国",
    tier: "NEARBY",
    story: "安岳的山石上保存着跨越多个朝代的石窟与雕像，人物、花纹和衣褶都由工匠一点点凿出。露天石刻也需要防雨、防风化和细心修复。",
    explore: "跟着星宠观察石头上深浅不同的刻痕，找找人物姿势和衣服纹样，并思考怎样参观才不会伤害文物。",
    funFact: "石刻看起来很坚硬，却会被雨水、温度变化和植物根系慢慢影响，因此保护工作需要长期进行。",
    scene: "temple",
  },
  {
    slug: "zhang-daqian-garden",
    name: "内江大千园",
    city: "内江",
    country: "中国",
    tier: "NEARBY",
    story: "大千园纪念画家张大千，展览用画作、印章和生活资料讲述他的艺术旅程。园林中的水面、石桥和植物也像一幅慢慢展开的中国画。",
    explore: "可以先看真实庭院，再看画家怎样用墨色表现远山和树木，试着用深浅不同的线画一片叶子。",
    funFact: "中国画里的墨加水后能产生很多深浅层次，画家常用这种变化表现雾、远山和光影。",
    scene: "museum",
  },
  {
    slug: "zigong-salt-museum",
    name: "自贡盐业历史博物馆",
    city: "自贡",
    country: "中国",
    tier: "NEARBY",
    story: "自贡因井盐闻名，博物馆展示古人怎样打出深井、提取地下卤水，再用火把水分蒸发得到盐。木制工具和井架记录着复杂的工程智慧。",
    explore: "跟着星宠观察钻井工具怎样一节节深入地下，再做一个小实验，看看盐水里的水蒸发后留下什么。",
    funFact: "古代自贡盐井能深入地下数百米，是世界上很早就达到巨大深度的钻井工程。",
    scene: "museum",
  },
  {
    slug: "zigong-lantern-world",
    name: "自贡彩灯大世界",
    city: "自贡",
    country: "中国",
    tier: "NEARBY",
    story: "自贡彩灯把竹篾、丝绸、金属骨架和现代灯光组合成会发亮的动物、花朵与故事场景。夜幕降临后，颜色和倒影让园区变成巨大的光影画册。",
    explore: "可以先猜一组彩灯内部用了什么形状的骨架，再观察灯光颜色怎样让同一个物体看起来远近不同。",
    funFact: "传统彩灯先搭立体骨架，再蒙上透光材料；今天还会加入机械、声音和数字控制技术。",
    scene: "garden",
  },
  {
    slug: "southern-sichuan-bamboo-sea",
    name: "蜀南竹海",
    city: "宜宾",
    country: "中国",
    tier: "NEARBY",
    story: "蜀南竹海覆盖着连绵山坡，竹林、湖泊、瀑布和栈道组成广阔的绿色世界。站在高处望去，风会让竹梢像海浪一样一层层移动。",
    explore: "跟着星宠听竹叶、溪水和鸟叫组成的声音，比较毛竹与其他竹子的粗细，再找找竹制生活用品。",
    funFact: "竹子地下有相连的竹鞭，新竹笋会从竹鞭上长出，因此一片竹林常常彼此连接。",
    scene: "forest",
  },
  {
    slug: "lizhuang-ancient-town",
    name: "李庄古镇",
    city: "宜宾",
    country: "中国",
    tier: "NEARBY",
    story: "李庄古镇坐在长江边，石板街、木建筑和老码头记录着水运生活。抗战时期，许多学校与文化机构搬到这里，坚持研究和教学。",
    explore: "可以寻找老建筑屋顶上的结构，观察江水与码头的关系，再听一听人们怎样在困难时期保护知识。",
    funFact: "营造学社曾在李庄研究中国古建筑，梁思成等学者在这里完成了重要的建筑史工作。",
    scene: "ancient-town",
  },
  {
    slug: "dazu-rock-carvings",
    name: "大足石刻",
    city: "重庆",
    country: "中国",
    tier: "NEARBY",
    story: "大足石刻分布在多处山崖，成千上万的雕像和故事画面由工匠在岩石上完成。人物表情、动物动作和生活场景让石头变得像会讲故事。",
    explore: "跟着星宠从一组石刻里找出开始、中间和结尾，观察工匠怎样用姿势与表情表现不同情绪。",
    funFact: "大足石刻中有不少劳动和家庭生活画面，因此也能帮助我们了解古人的日常生活。",
    scene: "temple",
  },
  {
    slug: "chongqing-natural-history-museum",
    name: "重庆自然博物馆",
    city: "重庆",
    country: "中国",
    tier: "NEARBY",
    story: "重庆自然博物馆收藏恐龙化石、矿物、动植物标本和关于山地环境的展览。巨大的骨架与细小昆虫放在一起，展示生命世界的不同尺度。",
    explore: "可以先站远看完整骨架，再走近观察牙齿和脚趾，猜测动物吃什么、怎样移动，并寻找证据。",
    funFact: "重庆和四川发现过许多侏罗纪恐龙化石，这些化石帮助科学家还原远古盆地的生态环境。",
    scene: "museum",
  },
];

const chinaDestinations: DestinationDraft[] = [
  {
    slug: "temple-of-heaven",
    name: "天坛",
    city: "北京",
    country: "中国",
    tier: "CHINA",
    story: "天坛是明清皇帝举行祭祀活动的建筑群，蓝色圆顶、红柱和白色石台层层向上。建筑用圆形象征天空，用方形表现大地，颜色与比例都经过认真设计。",
    explore: "跟着星宠沿中轴线观察祈年殿，从不同距离看屋顶大小变化，再找找圆形和方形怎样组合。",
    funFact: "回音壁光滑弯曲，声音会沿墙面传播；两个人站在合适位置，小声说话也可能被远处听见。",
    scene: "temple",
  },
  {
    slug: "summer-palace",
    name: "颐和园",
    city: "北京",
    country: "中国",
    tier: "CHINA",
    story: "颐和园把昆明湖、万寿山、长廊和园林建筑连成一幅巨大的山水画。湖面开阔，长廊彩画记录着人物、花鸟和传统故事。",
    explore: "可以跟着星宠数一段长廊里重复的梁柱，比较湖边与山上的视野，并选择一幅彩画讲出自己的故事。",
    funFact: "颐和园长廊全长七百多米，梁枋上绘有上万幅不同彩画，几乎找不到完全相同的两幅。",
    scene: "palace",
  },
  {
    slug: "national-museum-of-china",
    name: "中国国家博物馆",
    city: "北京",
    country: "中国",
    tier: "CHINA",
    story: "中国国家博物馆收藏从远古石器到近现代文物的大量历史见证。陶器、青铜器、书画和生活用品放在时间线上，帮助参观者理解社会怎样一步步变化。",
    explore: "跟着星宠挑选同一种用途的古今物品，比如灯、碗或车，比较材料、形状和使用方法有什么不同。",
    funFact: "司母戊鼎是馆内著名青铜器之一，铸造这样巨大的器物需要模具、熔炉和许多工匠合作。",
    scene: "museum",
  },
  {
    slug: "tianjin-eye",
    name: "天津之眼",
    city: "天津",
    country: "中国",
    tier: "CHINA",
    story: "天津之眼是一座跨在海河上的巨大摩天轮，桥梁让车辆过河，轮上的座舱又把游客慢慢送到高处。夜晚灯光会在河面形成长长倒影。",
    explore: "可以观察圆轮怎样围绕中心转动，数一数可见座舱，并想想座舱为什么始终保持底部朝下。",
    funFact: "天津之眼把摩天轮与桥梁结合在一起，是少见的建在桥上的大型观景轮。",
    scene: "tower",
  },
  {
    slug: "chengde-mountain-resort",
    name: "承德避暑山庄",
    city: "承德",
    country: "中国",
    tier: "CHINA",
    story: "避暑山庄是清代皇家园林，湖泊、平原、山地和宫殿被放进同一片广阔园区。建筑常顺着自然地形安排，让北方与江南风景在这里相遇。",
    explore: "跟着星宠在地图上分辨湖区、平原区和山区，比较三个区域的植物、道路和建筑为什么不同。",
    funFact: "山庄占地比北京故宫大很多，古人不用离开园区，也能体验多种不同的自然景观。",
    scene: "palace",
  },
  {
    slug: "shanhaiguan-pass",
    name: "山海关",
    city: "秦皇岛",
    country: "中国",
    tier: "CHINA",
    story: "山海关位于山脉与大海之间，是明长城东部的重要关城。城墙、城门、敌楼和远处山海组成严密防线，也见证了古代交通往来。",
    explore: "跟着星宠观察地形图，想一想为什么关城建在山与海之间，再寻找城墙上用来观察和防守的位置。",
    funFact: "附近的老龙头长城一直伸到海边，远看像巨龙把头探入渤海，因此得到了这个名字。",
    scene: "ancient-town",
  },
  {
    slug: "yungang-grottoes",
    name: "云冈石窟",
    city: "大同",
    country: "中国",
    tier: "CHINA",
    story: "云冈石窟开凿在山崖上，大大小小洞窟里保存着跨越一千五百多年的雕像与纹饰。不同洞窟的面容、服饰和造型反映了文化交流。",
    explore: "可以从远处看整体，再靠近观察手势、衣褶和莲花图案，比较早晚不同时期雕刻风格的变化。",
    funFact: "石窟工匠先在崖壁上规划洞窟，再从岩石中一点点向内开凿，不能像积木一样重新来过。",
    scene: "temple",
  },
  {
    slug: "pingyao-ancient-city",
    name: "平遥古城",
    city: "晋中",
    country: "中国",
    tier: "CHINA",
    story: "平遥古城保存着完整城墙、街巷、票号和传统院落，登上城墙能看见灰色屋顶铺满城内。这里曾是中国重要的金融与商业中心。",
    explore: "跟着星宠在城门、街道和院落之间画一张简单路线图，再看看老票号怎样记录远方的钱款往来。",
    funFact: "日升昌票号曾用密押和汇票帮助商人异地取款，是中国早期金融机构的代表。",
    scene: "ancient-town",
  },
  {
    slug: "hukou-waterfall",
    name: "壶口瀑布",
    city: "临汾",
    country: "中国",
    tier: "CHINA",
    story: "黄河来到壶口时，宽阔河面突然被两岸岩石挤进狭窄河槽，巨量河水翻滚而下。水雾、轰鸣和黄色浪花展示出河流强大的力量。",
    explore: "可以站在安全观景区观察河面由宽变窄，听声音与距离的关系，并想象流水怎样不断改变岩石。",
    funFact: "“壶口”形容河水像从巨大茶壶口倾倒出来，瀑布位置还会因长期侵蚀缓慢变化。",
    scene: "waterfall",
  },
  {
    slug: "longmen-grottoes",
    name: "龙门石窟",
    city: "洛阳",
    country: "中国",
    tier: "CHINA",
    story: "龙门石窟分布在伊河两岸山崖上，洞窟、雕像和题记记录了多个朝代的艺术。最大的造像气势庄严，最小的雕刻只有指尖大小。",
    explore: "跟着星宠比较巨大与微小造像的比例，寻找不同表情和服饰，再观察河流为什么适合成为古代交通通道。",
    funFact: "龙门石窟留下了大量题记，文字不仅记录造像原因，也帮助研究古代书法和语言。",
    scene: "temple",
  },
  {
    slug: "shaolin-temple",
    name: "少林寺",
    city: "登封",
    country: "中国",
    tier: "CHINA",
    story: "少林寺坐落在嵩山林间，以古建筑、塔林和武术文化闻名。练习武术不仅需要力量，也要学习平衡、节奏、耐心与尊重。",
    explore: "可以观察简单动作怎样保持身体重心，找找寺院建筑的中轴与对称，但不要模仿高难度动作。",
    funFact: "少林寺塔林由许多不同时期的砖石塔组成，塔的层数、形状和雕刻各不相同。",
    scene: "temple",
  },
  {
    slug: "millennium-city-park",
    name: "清明上河园",
    city: "开封",
    country: "中国",
    tier: "CHINA",
    story: "清明上河园把古画《清明上河图》中的街市、桥梁、店铺和人物活动变成立体园区。船只、作坊和表演让人想象北宋城市的繁忙一天。",
    explore: "跟着星宠寻找画中与园中的同一个场景，观察古代商店怎样招揽客人，再比较当时和今天的交通工具。",
    funFact: "《清明上河图》画卷很长，人物超过八百个，仔细看还能发现许多小动物和生活细节。",
    scene: "ancient-town",
  },
  {
    slug: "mount-tai",
    name: "泰山",
    city: "泰安",
    country: "中国",
    tier: "CHINA",
    story: "泰山从华北平原拔地而起，石阶、古树、碑刻和寺庙沿山路向上延伸。许多帝王、文人和普通旅行者都曾在这里留下足迹。",
    explore: "跟着星宠比较山脚与山顶的植物和天气，观察石阶怎样适应坡度，并寻找岩石上的古代文字。",
    funFact: "泰山石刻数量很多，从不同朝代的碑文里可以看到汉字书写风格如何发生变化。",
    scene: "mountain",
  },
  {
    slug: "qufu-confucian-sites",
    name: "曲阜三孔",
    city: "曲阜",
    country: "中国",
    tier: "CHINA",
    story: "曲阜的孔庙、孔府和孔林合称“三孔”，建筑、古树和碑刻记录着尊师重教的传统。院落沿中轴层层展开，像一本关于教育的历史书。",
    explore: "可以寻找建筑中的对称与等级变化，读一条关于学习的短句，再说说自己最喜欢怎样探索新知识。",
    funFact: "孔林里生长着大量古树，不同年代的人们种下它们，使这里也成为一座珍贵的古树园。",
    scene: "temple",
  },
  {
    slug: "qingdao-zhanqiao-pier",
    name: "青岛栈桥",
    city: "青岛",
    country: "中国",
    tier: "CHINA",
    story: "栈桥从青岛海岸伸向海中，尽头的回澜阁与红瓦城市隔海相望。潮水涨落时，桥下礁石会出现又隐藏，海鸥也常跟随浪花飞行。",
    explore: "跟着星宠观察潮位变化和浪花方向，比较礁石上湿润与干燥的区域，并记住不要靠近危险浪区。",
    funFact: "潮汐主要受到月球和太阳引力影响，同一天不同时间，海面高度会有规律地升降。",
    scene: "ocean",
  },
  {
    slug: "nanjing-museum",
    name: "南京博物院",
    city: "南京",
    country: "中国",
    tier: "CHINA",
    story: "南京博物院收藏考古文物、书画、陶瓷和民俗物件，还复原了近代街景。走过不同展厅，就能看到技术、审美与日常生活怎样变化。",
    explore: "跟着星宠选择一件最想带回家的古代用品，先弄懂它的用途，再设计一个今天更方便使用的版本。",
    funFact: "博物院的历史馆建筑外形借鉴传统宫殿，却使用了现代结构，是新旧建筑结合的例子。",
    scene: "museum",
  },
  {
    slug: "sun-yat-sen-mausoleum",
    name: "中山陵",
    city: "南京",
    country: "中国",
    tier: "CHINA",
    story: "中山陵依紫金山山势修建，从入口到祭堂有长长石阶和宽阔平台。蓝色琉璃瓦、白色石墙与绿色山林形成庄重清晰的色彩。",
    explore: "可以从低处和高处分别观察石阶，感受透视让台阶怎样变化，并数一数平台把攀登分成几段。",
    funFact: "从下往上看常只见台阶，从上往下看却更容易看到平台，设计利用了视角变化。",
    scene: "palace",
  },
  {
    slug: "suzhou-classical-gardens",
    name: "苏州古典园林",
    city: "苏州",
    country: "中国",
    tier: "CHINA",
    story: "苏州园林用池水、假山、花窗、长廊和植物在不大的空间里创造丰富景色。转过一扇门或一段墙，眼前画面就会重新组合。",
    explore: "跟着星宠透过不同花窗看同一处景物，比较框住以后画面有什么变化，再找一条曲折小路走走。",
    funFact: "园林常使用“借景”，把远处的塔、山或天空纳入眼前画面，让空间看起来更大。",
    scene: "garden",
  },
  {
    slug: "wuzhen-water-town",
    name: "乌镇",
    city: "嘉兴",
    country: "中国",
    tier: "CHINA",
    story: "乌镇的河道穿过白墙黑瓦的房屋，石桥把两岸小巷连接起来，木船曾是重要交通工具。临水建筑让居民开门就能看见河。",
    explore: "跟着星宠观察桥洞形状与船只高度的关系，比较水路和陆路怎样到达同一个地方。",
    funFact: "江南水乡河网密集，过去运送粮食、布匹和生活用品时，船往往比车辆更方便。",
    scene: "ancient-town",
  },
  {
    slug: "thousand-island-lake",
    name: "千岛湖",
    city: "杭州",
    country: "中国",
    tier: "CHINA",
    story: "千岛湖是新安江水库形成的广阔湖泊，水位升高后，许多山峰变成大小不同的岛屿。森林覆盖的岛屿与弯曲湖湾从高处看格外清晰。",
    explore: "跟着星宠在地图上寻找半岛和岛屿，想一想水位变化为什么会改变山峰形状，并讨论怎样保护清洁水源。",
    funFact: "“千岛”不是夸张说法，湖中达到一定面积的岛屿确实超过一千座。",
    scene: "lake",
  },
  {
    slug: "wuyuan-huangling",
    name: "婺源篁岭",
    city: "上饶",
    country: "中国",
    tier: "CHINA",
    story: "篁岭村建在山坡上，房屋顺地势层层排列，秋天人们把辣椒、玉米和稻谷放在晒架上晾晒。红黄作物与黑瓦白墙组成鲜明图案。",
    explore: "跟着星宠观察不同作物的颜色、形状和排列，想一想为什么要晒干，再寻找房屋适应坡地的方法。",
    funFact: "“晒秋”并不只发生在秋天，而是山地村民利用屋顶和晒架晾晒农作物的生活方式。",
    scene: "ancient-town",
  },
  {
    slug: "mount-lu",
    name: "庐山",
    city: "九江",
    country: "中国",
    tier: "CHINA",
    story: "庐山靠近长江和鄱阳湖，山峰、瀑布、云雾与林间建筑共同形成多变景色。许多诗人从不同角度描写它，也发现山的样子会随观察位置改变。",
    explore: "跟着星宠换三个方向看同一座山峰，比较轮廓差别，再用自己的话解释“不识庐山真面目”。",
    funFact: "湿润空气沿山坡上升后冷却，水汽凝结成云雾，所以庐山常被流动云层包围。",
    scene: "mountain",
  },
  {
    slug: "jingdezhen-ceramics-museum",
    name: "景德镇中国陶瓷博物馆",
    city: "景德镇",
    country: "中国",
    tier: "CHINA",
    story: "景德镇以制瓷闻名，博物馆展示泥土怎样经过拉坯、绘画、上釉和高温烧制变成瓷器。不同时代的颜色、纹样和器形各有特点。",
    explore: "跟着星宠寻找圆形器物的对称轴，比较釉色深浅，再把一种植物设计成连续的瓷器花纹。",
    funFact: "瓷器烧制温度通常比普通陶器更高，胎体会更致密，敲击时也常发出清脆声音。",
    scene: "museum",
  },
  {
    slug: "wuyi-mountain",
    name: "武夷山",
    city: "武夷山",
    country: "中国",
    tier: "CHINA",
    story: "武夷山的红色岩壁、曲折溪流、森林和茶园组合成独特的丹霞景观。竹筏顺九曲溪缓慢前行，可以从水面仰望山峰变化。",
    explore: "跟着星宠数溪流转弯次数，观察河水怎样绕过岩石，再比较向阳与背阴岩壁的植物。",
    funFact: "武夷岩茶生长在岩壁与山谷间，不同小环境会影响茶叶香气，因此有“岩韵”的说法。",
    scene: "mountain",
  },
  {
    slug: "fujian-tulou",
    name: "福建土楼",
    city: "龙岩",
    country: "中国",
    tier: "CHINA",
    story: "福建土楼用夯土筑成厚实外墙，圆形或方形大楼围住共同院落，许多家庭能住在同一座建筑里。结构兼顾生活、防护和邻里合作。",
    explore: "跟着星宠从俯视图寻找圆、方和中心点，想一想厨房、仓库与卧室怎样安排才方便大家共同生活。",
    funFact: "夯土墙由泥土、砂石等材料分层压实，厚墙冬暖夏凉，还能承受风雨。",
    scene: "ancient-town",
  },
  {
    slug: "gulangyu-island",
    name: "鼓浪屿",
    city: "厦门",
    country: "中国",
    tier: "CHINA",
    story: "鼓浪屿隔海面对厦门，岛上有不同风格建筑、海边岩石和安静小路。钢琴音乐与海浪声常被联系在一起，车辆很少让步行更自在。",
    explore: "跟着星宠寻找屋顶、窗户和门廊的不同样式，听海浪节奏，再比较岛上道路与大城市街道。",
    funFact: "鼓浪屿拥有很多钢琴，长期的音乐教育与家庭演奏传统让它被称为“钢琴之岛”。",
    scene: "island",
  },
  {
    slug: "yellow-crane-tower",
    name: "黄鹤楼",
    city: "武汉",
    country: "中国",
    tier: "CHINA",
    story: "黄鹤楼矗立在长江边的蛇山上，金色屋顶层层展开，可以远眺江水、桥梁和城市。历代诗歌让这座楼与送别、远行和想象联系在一起。",
    explore: "跟着星宠登高观察船只为什么看起来变小，找一句熟悉诗句，再把江面上的景物按远近排队。",
    funFact: "今天的黄鹤楼经过重建，保留传统外观的同时使用了现代建筑材料和结构。",
    scene: "tower",
  },
  {
    slug: "zhangjiajie-national-forest-park",
    name: "张家界国家森林公园",
    city: "张家界",
    country: "中国",
    tier: "CHINA",
    story: "张家界有成片高耸石柱，云雾在柱峰之间流动，森林从谷底一直长到峰顶。流水、风化和漫长地质变化塑造了今天的奇特地貌。",
    explore: "跟着星宠比较石柱粗细和顶部植物，观察云雾遮挡前后的空间感，并在安全观景台寻找最像动物的一座峰。",
    funFact: "这里的柱状峰林主要由石英砂岩构成，岩石中的垂直裂隙帮助它们逐渐分离成独立峰柱。",
    scene: "mountain",
  },
  {
    slug: "yueyang-tower",
    name: "岳阳楼",
    city: "岳阳",
    country: "中国",
    tier: "CHINA",
    story: "岳阳楼临近洞庭湖，木结构楼阁从高处眺望湖面与远山。古代文章把这里的晴雨风景和关心天下的胸怀写在一起。",
    explore: "跟着星宠比较晴天与雨天的湖面想象，观察木柱怎样支撑屋顶，再说说旅行中怎样照顾同伴。",
    funFact: "岳阳楼主楼没有使用一颗铁钉，而是依靠木构件之间的榫卯相互咬合。",
    scene: "tower",
  },
  {
    slug: "orange-isle",
    name: "橘子洲",
    city: "长沙",
    country: "中国",
    tier: "CHINA",
    story: "橘子洲是湘江中的长形沙洲，树木、步道和亲水空间沿江铺开，两岸城市隔水相望。江流会不断搬运泥沙，也塑造洲岛形状。",
    explore: "跟着星宠在地图上辨认江、岸和洲，观察水流方向，再比较站在洲头与洲尾看到的景色。",
    funFact: "沙洲由河流携带的泥沙在水流较缓处逐渐堆积形成，形状可能随洪水和季节改变。",
    scene: "garden",
  },
  {
    slug: "li-river-guilin",
    name: "桂林漓江",
    city: "桂林",
    country: "中国",
    tier: "CHINA",
    story: "漓江穿过一座座陡峭喀斯特山峰，清水、竹林、田野和倒影组成层次丰富的山水。不同角度的山峰常让人联想到动物和人物。",
    explore: "跟着星宠寻找象鼻、骆驼或其他想象形状，观察倒影被船波打散后怎样重新出现。",
    funFact: "桂林峰林来自可溶性石灰岩，雨水和地下水经过极长时间溶蚀，留下今天的山峰与洞穴。",
    scene: "mountain",
  },
  {
    slug: "canton-tower",
    name: "广州塔",
    city: "广州",
    country: "中国",
    tier: "CHINA",
    story: "广州塔由交叉钢结构编织成细腰形外观，夜晚会显示多彩灯光。登高后，珠江、桥梁和密集城市道路像模型一样展开。",
    explore: "跟着星宠观察钢条交叉形成的菱形，想一想塔身为什么中间变细，再从高处寻找弯曲珠江。",
    funFact: "塔的外框由斜向钢柱和环形构件组成，旋转变化让它看起来像轻轻扭转。",
    scene: "tower",
  },
  {
    slug: "zhuhai-ocean-kingdom",
    name: "珠海长隆海洋王国",
    city: "珠海",
    country: "中国",
    tier: "CHINA",
    story: "海洋王国通过大型水族箱和科普展示介绍鲸鲨、鳐鱼、珊瑚与极地动物。不同展区模拟海洋深浅和温度，让孩子理解水下世界并不完全相同。",
    explore: "跟着星宠观察鱼群怎样转向而不撞在一起，比较鲸鲨与小鱼的身体比例，并学习不乱丢塑料垃圾。",
    funFact: "鲸鲨虽然名字里有“鲸”，其实是世界上体型最大的鱼，主要过滤海水中的小生物进食。",
    scene: "ocean",
  },
  {
    slug: "shenzhen-astronomical-observatory",
    name: "深圳天文台",
    city: "深圳",
    country: "中国",
    tier: "CHINA",
    story: "深圳天文台建在海边山地，圆顶望远镜、气象设备和栈道面向广阔天空与海洋。这里既观察星空，也记录风、云和天气变化。",
    explore: "跟着星宠认一认东南西北，白天观察云层，夜晚寻找最亮星星，并理解望远镜不能直接看太阳。",
    funFact: "天文望远镜收集的光越多，就越能看见暗弱遥远的天体，因此镜面大小十分重要。",
    scene: "science",
  },
  {
    slug: "yalong-bay",
    name: "三亚亚龙湾",
    city: "三亚",
    country: "中国",
    tier: "CHINA",
    story: "亚龙湾有弯月形沙滩、热带植物和清澈海水，近岸浅水颜色比远处更明亮。海浪不断搬动细沙，也会留下贝壳与小动物活动痕迹。",
    explore: "跟着星宠比较干沙和湿沙能搭出的形状，观察浪线在哪里停下，并牢记只在安全区域亲近海水。",
    funFact: "沙粒来自岩石、贝壳等材料长期破碎，不同海滩的矿物组成会让沙子呈现不同颜色。",
    scene: "ocean",
  },
  {
    slug: "haikou-volcano-park",
    name: "海口火山口公园",
    city: "海口",
    country: "中国",
    tier: "CHINA",
    story: "海口火山口公园保存着古老火山口、熔岩隧道和由火山岩形成的黑色石头。今天这里覆盖热带植物，说明自然能在冷却岩石上重新生长。",
    explore: "跟着星宠观察火山岩上的小孔，想象气泡怎样被凝固岩浆留下，再寻找植物扎根的土壤从哪里来。",
    funFact: "火山岩中的许多小孔，是岩浆冷却时气体来不及逃出留下的，像石头里的气泡印章。",
    scene: "mountain",
  },
  {
    slug: "detian-waterfall",
    name: "德天瀑布",
    city: "崇左",
    country: "中国",
    tier: "CHINA",
    story: "德天瀑布位于中国与越南边境，归春河从层层岩壁跌落，分成多股白色水帘。青山、稻田和河流共同形成湿润的南方边境风景。",
    explore: "跟着星宠观察瀑布分成几层，比较雨季与旱季水量，并在地图上找到河流穿过的国界。",
    funFact: "德天瀑布是一座跨国瀑布，同一条河流的水景由两个国家共同分享与保护。",
    scene: "waterfall",
  },
  {
    slug: "huangguoshu-waterfall",
    name: "黄果树瀑布",
    city: "安顺",
    country: "中国",
    tier: "CHINA",
    story: "黄果树瀑布宽阔水流从高崖落入河谷，水雾在阳光下有时会出现彩虹。瀑布后方还有天然洞穴，让人能从不同方向感受水的力量。",
    explore: "跟着星宠从正面、侧面和远处观察瀑布，听声音变化，并找找彩虹需要阳光和水滴同时出现的证据。",
    funFact: "水帘洞位于瀑布后方，穿过洞中窗口可以从背面看见倾泻而下的水幕。",
    scene: "waterfall",
  },
  {
    slug: "libo-small-seven-hole",
    name: "荔波小七孔",
    city: "黔南",
    country: "中国",
    tier: "CHINA",
    story: "小七孔景区有古石桥、碧绿河水、瀑布和喀斯特森林，水在岩石与树根之间穿行。清澈水色来自光线、深度和矿物环境共同作用。",
    explore: "跟着星宠数石桥桥孔，观察急流与静水颜色差别，再寻找喜欢生长在潮湿岩石上的植物。",
    funFact: "小七孔桥建于清代，七个桥孔既让水流通过，也使石桥把重量稳稳传向两岸。",
    scene: "forest",
  },
  {
    slug: "stone-forest-yunnan",
    name: "云南石林",
    city: "昆明",
    country: "中国",
    tier: "CHINA",
    story: "云南石林由密集石灰岩柱组成，尖峰、石墙和狭窄通道像一片不会生长的灰色森林。地下水与雨水经过极长时间溶解岩石，留下奇特形状。",
    explore: "跟着星宠在安全路线寻找像动物的石峰，触摸前先遵守规定，并用纸画出岩石轮廓。",
    funFact: "石林地区远古时期曾被海水覆盖，岩石里还可能保存海洋生物留下的化石线索。",
    scene: "mountain",
  },
  {
    slug: "lijiang-ancient-town",
    name: "丽江古城",
    city: "丽江",
    country: "中国",
    tier: "CHINA",
    story: "丽江古城的石板路、水渠、木屋和小桥顺着山地自然展开，雪山融水流进街巷。纳西族文化、东巴文字和传统音乐让古城拥有独特声音与符号。",
    explore: "跟着星宠沿水流辨认方向，寻找东巴象形文字像什么图画，并观察院落怎样利用阳光和水。",
    funFact: "丽江古城没有规整城墙，街道像水网一样自然生长，第一次来的人很容易觉得它像迷宫。",
    scene: "ancient-town",
  },
  {
    slug: "erhai-lake",
    name: "大理洱海",
    city: "大理",
    country: "中国",
    tier: "CHINA",
    story: "洱海是苍山脚下的高原湖泊，形状像一只长长耳朵，湖边有湿地、村庄和农田。云朵、山峰与水面倒影会随着天气不断变化。",
    explore: "跟着星宠观察水鸟、芦苇和远山，比较上午与傍晚水面颜色，并讨论怎样减少污染保护湖泊。",
    funFact: "洱海其实是一座淡水湖，“海”是当地人对宽阔水域的亲切称呼。",
    scene: "lake",
  },
  {
    slug: "xishuangbanna-tropical-botanical-garden",
    name: "西双版纳热带植物园",
    city: "西双版纳",
    country: "中国",
    tier: "CHINA",
    story: "植物园收集大量热带植物，高大的棕榈、会变色的花和巨大叶片展示湿热环境里的生命多样性。不同植物用刺、气味和特殊叶形适应周围世界。",
    explore: "跟着星宠寻找最大叶片、最特别树皮和最香花朵，只用眼睛和鼻子观察，不随意触碰陌生植物。",
    funFact: "王莲叶片内部有坚固放射状叶脉，像支架一样分散重量，因此能稳稳浮在水面。",
    scene: "forest",
  },
  {
    slug: "mogao-caves",
    name: "莫高窟",
    city: "敦煌",
    country: "中国",
    tier: "CHINA",
    story: "莫高窟开凿在敦煌鸣沙山东麓，洞窟里的壁画、彩塑和经卷记录古代丝绸之路上的交流。颜色、服饰、乐器和动物都讲述远方文化相遇的故事。",
    explore: "跟着星宠观察壁画中的飞天、乐器和纹样，寻找从不同地区来到敦煌的线索，并学习用低光保护文物。",
    funFact: "壁画颜料来自矿物和植物，一些颜色经过上千年仍能看见，但光线和湿度会让它们慢慢变化。",
    scene: "desert",
  },
  {
    slug: "jiayuguan-pass",
    name: "嘉峪关",
    city: "嘉峪关",
    country: "中国",
    tier: "CHINA",
    story: "嘉峪关城楼坐落在河西走廊西部，远处祁连雪山与戈壁衬托出坚固城墙。它是明长城西端重要关隘，也是古代东西交通的节点。",
    explore: "跟着星宠观察城门一层层防护的设计，在地图上找河西走廊，想想商队为什么选择这条狭长通道。",
    funFact: "嘉峪关城墙主要用黄土夯筑，工匠会分层压实，让看似松散的土变得坚固。",
    scene: "desert",
  },
  {
    slug: "qinghai-lake",
    name: "青海湖",
    city: "海北",
    country: "中国",
    tier: "CHINA",
    story: "青海湖是高原上的巨大咸水湖，蓝色水面周围有草原、雪山和候鸟栖息地。夏季油菜花盛开时，黄、蓝、绿三种颜色铺向远方。",
    explore: "跟着星宠观察高原风吹动草地和湖面，寻找候鸟但保持距离，再比较咸水湖与淡水湖。",
    funFact: "青海湖没有河流把水送入大海，水分主要靠蒸发离开，因此盐分逐渐积累成咸水湖。",
    scene: "lake",
  },
  {
    slug: "kanas-lake",
    name: "喀纳斯湖",
    city: "阿勒泰",
    country: "中国",
    tier: "CHINA",
    story: "喀纳斯湖藏在阿尔泰山森林与雪峰之间，湖水会因天气、光线和泥沙变化呈现不同蓝绿色。秋天树林变成金黄与橙红，像一条彩色山谷。",
    explore: "跟着星宠比较阴天与晴天湖色，观察针叶林怎样适应寒冷，并在地图上找到中国西北边疆。",
    funFact: "喀纳斯湖由古代冰川运动塑造，冰川搬运和侵蚀留下了深湖与宽阔山谷。",
    scene: "lake",
  },
  {
    slug: "tianchi-tianshan",
    name: "天山天池",
    city: "昌吉",
    country: "中国",
    tier: "CHINA",
    story: "天山天池位于雪山脚下，深色针叶林围住清澈高山湖，远处博格达峰常年积雪。湖面平静时，雪峰会完整倒映在水中。",
    explore: "跟着星宠找出雪线、森林线和湖岸，想一想高度变化为什么会让植物越来越少、气温越来越低。",
    funFact: "天池是古冰川活动形成的高山湖泊，冰川像巨大推土机一样改变了山谷地形。",
    scene: "mountain",
  },
  {
    slug: "hulunbuir-grassland",
    name: "呼伦贝尔草原",
    city: "呼伦贝尔",
    country: "中国",
    tier: "CHINA",
    story: "呼伦贝尔草原地势开阔，河流弯曲穿过草地，牛羊和马群在远处移动。天空看起来格外宽大，季节会把草原从嫩绿变成金黄与雪白。",
    explore: "跟着星宠观察风向、云影和动物队伍，比较草原与森林的视野，并学习不惊扰牧群。",
    funFact: "草原植物的生长点常靠近地面，即使上部被动物吃掉，也能继续生长，这是适应放牧的重要特点。",
    scene: "grassland",
  },
  {
    slug: "harbin-ice-snow-world",
    name: "哈尔滨冰雪大世界",
    city: "哈尔滨",
    country: "中国",
    tier: "CHINA",
    story: "冬天的哈尔滨用巨大冰块和积雪建造城堡、滑梯与雕塑，灯光从透明冰体内部亮起。严寒让建筑保持形状，也让夜晚像彩色水晶世界。",
    explore: "跟着星宠观察冰砖怎样排列，比较冰与雪的透明度，记得穿好保暖衣物并让身体适当休息。",
    funFact: "冰雕使用的冰块越清澈，内部气泡和杂质越少，灯光穿过时就越像透明玻璃。",
    scene: "ice",
  },
];

const worldDestinations: DestinationDraft[] = [
  {
    slug: "statue-of-liberty",
    name: "自由女神像",
    city: "纽约",
    country: "美国",
    tier: "WORLD",
    story: "自由女神像站在纽约港入口，高举火炬迎接乘船来到城市的人们。铜制外表经过多年风雨变成绿色，脚下断开的锁链象征摆脱束缚。",
    explore: "跟着星宠观察雕像手中的火炬、书板和王冠，把这些符号与“自由”这个词联系起来。",
    funFact: "雕像最初不是绿色，而是铜的棕红色；铜与空气长期反应后形成绿色保护层。",
    scene: "tower",
  },
  {
    slug: "golden-gate-bridge",
    name: "金门大桥",
    city: "旧金山",
    country: "美国",
    tier: "WORLD",
    story: "金门大桥横跨海峡，两座高塔用粗大主缆吊起桥面，橙红色在海雾中仍很醒目。桥下海水连接太平洋与旧金山湾，风浪和船只不断经过。",
    explore: "跟着星宠观察主缆怎样变成许多竖直吊索，想一想桥面重量如何传到塔和两岸。",
    funFact: "大桥常被海雾包围，专门选择的“国际橙”既漂亮，也能提高雾中的可见度。",
    scene: "city",
  },
  {
    slug: "grand-canyon",
    name: "科罗拉多大峡谷",
    city: "亚利桑那州",
    country: "美国",
    tier: "WORLD",
    story: "大峡谷像一本被河流切开的地球历史书，不同颜色岩层记录着漫长年代。科罗拉多河在谷底流动，阳光角度会让峭壁颜色不断变化。",
    explore: "跟着星宠从上到下观察岩层颜色，想象流水、风和温度怎样一点点扩大峡谷，并始终远离边缘。",
    funFact: "峡谷岩层最老部分超过十亿年，而今天看到的深谷主要由河流在数百万年中不断下切形成。",
    scene: "desert",
  },
  {
    slug: "yellowstone-national-park",
    name: "黄石国家公园",
    city: "怀俄明州",
    country: "美国",
    tier: "WORLD",
    story: "黄石公园有间歇泉、温泉、峡谷和广阔森林，地下热量让热水与蒸汽从地面喷出。野牛、鹿和熊生活在这里，人们必须保持安全距离。",
    explore: "跟着星宠观察彩色温泉边缘的颜色变化，寻找动物足迹，但只走步道、不接近滚烫水面。",
    funFact: "温泉的蓝、黄、橙等颜色与水温和微生物有关，不同温度适合不同种类生活。",
    scene: "wildlife",
  },
  {
    slug: "niagara-falls",
    name: "尼亚加拉瀑布",
    city: "安大略",
    country: "加拿大",
    tier: "WORLD",
    story: "尼亚加拉瀑布位于加拿大与美国边境，宽阔河流分成多段跌落，制造持续轰鸣和巨大水雾。夜晚灯光会照亮水幕，冬天边缘还可能结冰。",
    explore: "跟着星宠在地图上找到国界与河流，比较马蹄形瀑布和其他瀑布轮廓，再观察水雾飘向哪里。",
    funFact: "瀑布水流也被用来发电，水推动涡轮旋转后，可以把运动能量转换成电能。",
    scene: "waterfall",
  },
  {
    slug: "banff-national-park",
    name: "班夫国家公园",
    city: "艾伯塔",
    country: "加拿大",
    tier: "WORLD",
    story: "班夫位于落基山脉，雪山、冰川湖、针叶林和草甸组成辽阔自然景观。湖水里的细小岩粉会散射光线，让水面呈现明亮蓝绿色。",
    explore: "跟着星宠观察雪线、森林和湖岸的高度关系，寻找动物时保持距离，并把看到的颜色做成自然色卡。",
    funFact: "路易斯湖的蓝绿色来自冰川磨出的细小岩粉，这些颗粒会把蓝绿光反射到眼睛里。",
    scene: "mountain",
  },
  {
    slug: "chichen-itza",
    name: "奇琴伊察",
    city: "尤卡坦",
    country: "墨西哥",
    tier: "WORLD",
    story: "奇琴伊察是玛雅文明留下的古城，阶梯金字塔、球场和天文建筑展示了数学与观测天空的知识。石头表面还刻着羽蛇、武士和动物图案。",
    explore: "跟着星宠数金字塔台阶的层次，观察光影怎样改变建筑轮廓，再在地图上找到尤卡坦半岛。",
    funFact: "春分和秋分附近，金字塔栏杆会出现连续三角形阴影，看起来像一条羽蛇沿台阶移动。",
    scene: "temple",
  },
  {
    slug: "christ-the-redeemer",
    name: "里约热内卢基督像",
    city: "里约热内卢",
    country: "巴西",
    tier: "WORLD",
    story: "巨大的基督像张开双臂站在科尔科瓦多山顶，俯瞰海湾、城市与绿色山林。雕像外层铺着许多小块皂石，能经受山顶风雨。",
    explore: "跟着星宠从远处观察雕像与山的比例，再张开手臂感受姿势带来的欢迎与拥抱含义。",
    funFact: "雕像内部是钢筋混凝土结构，表面由工人手工贴上大量三角形皂石小片。",
    scene: "mountain",
  },
  {
    slug: "iguazu-falls",
    name: "伊瓜苏瀑布",
    city: "米西奥内斯",
    country: "阿根廷",
    tier: "WORLD",
    story: "伊瓜苏瀑布群由两百多条大小瀑布组成，分布在阿根廷与巴西边境的热带森林中。水流从马蹄形悬崖落下，水雾滋养附近植物与动物。",
    explore: "跟着星宠数一数视野里能看到的水帘，听森林和瀑布共同发出的声音，并寻找彩虹。",
    funFact: "“伊瓜苏”来自当地语言，意思接近“大水”，瀑布最壮观处被称为“魔鬼咽喉”。",
    scene: "waterfall",
  },
  {
    slug: "machu-picchu",
    name: "马丘比丘",
    city: "库斯科",
    country: "秘鲁",
    tier: "WORLD",
    story: "马丘比丘建在安第斯山高处，石墙、梯田和神庙被云雾与群峰包围。印加工匠把巨石紧密拼合，并用梯田稳定山坡、种植作物。",
    explore: "跟着星宠观察石块之间几乎没有缝隙，比较梯田一层层排列的作用，再找找羊驼的身影。",
    funFact: "许多石墙没有使用灰浆，工匠把石头反复打磨到紧密吻合，使建筑更能适应地震晃动。",
    scene: "mountain",
  },
  {
    slug: "easter-island-moai",
    name: "复活节岛摩艾石像",
    city: "复活节岛",
    country: "智利",
    tier: "WORLD",
    story: "复活节岛位于南太平洋，巨大的摩艾石像面向岛内站立，长脸、宽鼻和深眼窝形成独特外观。它们由岛上火山岩雕刻，代表祖先与守护力量。",
    explore: "跟着星宠比较不同石像的高矮和帽子，想一想没有现代机器的人们可能怎样搬运它们。",
    funFact: "许多摩艾不只有露在地面的头部，地下还埋着完整身体和刻在背后的图案。",
    scene: "island",
  },
  {
    slug: "stonehenge",
    name: "巨石阵",
    city: "威尔特郡",
    country: "英国",
    tier: "WORLD",
    story: "巨石阵由一圈圈巨大石块组成，部分横石像门梁一样架在立石上。它建成于几千年前，与太阳升落方向和古代仪式可能有关。",
    explore: "跟着星宠观察石块排列与圆形，想一想古人怎样搬运和竖起巨石，再找夏至日出方向。",
    funFact: "部分蓝砂石来自两百多公里外，说明古代人曾用陆路和水路进行漫长运输。",
    scene: "grassland",
  },
  {
    slug: "big-ben",
    name: "大本钟与威斯敏斯特宫",
    city: "伦敦",
    country: "英国",
    tier: "WORLD",
    story: "伊丽莎白塔矗立在泰晤士河边，四面钟盘让不同方向的人都能看见时间。旁边的威斯敏斯特宫有尖塔、长廊和密集窗格，是英国议会所在地。",
    explore: "跟着星宠读一读钟面时间，观察分针走一圈时针走多远，再寻找建筑重复出现的尖拱。",
    funFact: "“大本钟”原本主要指塔内最大的一口钟，后来人们也常用它称呼整座钟塔。",
    scene: "tower",
  },
  {
    slug: "colosseum-rome",
    name: "罗马斗兽场",
    city: "罗马",
    country: "意大利",
    tier: "WORLD",
    story: "罗马斗兽场是一座巨大的椭圆形古代竞技场，多层拱门把人群引向不同座位。地下通道曾用来准备表演者、动物和舞台机关。",
    explore: "跟着星宠从俯视图寻找椭圆和中心舞台，观察拱券怎样支撑重量，再比较古今大型场馆。",
    funFact: "斗兽场设置许多入口和通道，几万名观众能够较快进出，这种组织方式影响了现代体育场设计。",
    scene: "ancient-town",
  },
  {
    slug: "venice-grand-canal",
    name: "威尼斯大运河",
    city: "威尼斯",
    country: "意大利",
    tier: "WORLD",
    story: "威尼斯建在潟湖岛屿上，大运河像一条弯曲主街穿过城市，船承担公交、运货和救援工作。宫殿与房屋把入口直接开向水面。",
    explore: "跟着星宠比较贡多拉、水上巴士和陆地车辆，在地图上寻找桥梁，并观察水位与台阶关系。",
    funFact: "威尼斯许多建筑由打入泥层的木桩支撑，木桩长期缺少氧气，反而不容易腐烂。",
    scene: "city",
  },
  {
    slug: "sagrada-familia",
    name: "圣家堂",
    city: "巴塞罗那",
    country: "西班牙",
    tier: "WORLD",
    story: "圣家堂由建筑师高迪设计，高塔、彩色玻璃和像树干一样分叉的柱子充满自然灵感。阳光穿过玻璃时，会把室内染成不断移动的彩色森林。",
    explore: "跟着星宠寻找像树、叶、蜂巢和贝壳的建筑细节，观察上午与下午光线颜色有什么不同。",
    funFact: "教堂从十九世纪开始建造，直到今天仍在继续施工，是一座跨越多代人的建筑工程。",
    scene: "temple",
  },
  {
    slug: "alhambra-palace",
    name: "阿尔罕布拉宫",
    city: "格拉纳达",
    country: "西班牙",
    tier: "WORLD",
    story: "阿尔罕布拉宫坐在山丘上，庭院、水池、喷泉与密集几何花纹组成细腻空间。水不仅带来清凉，也通过倒影和声音让建筑更有层次。",
    explore: "跟着星宠寻找能不断重复铺满墙面的图案，比较镜面水池里的倒影，并听喷泉怎样改变安静庭院。",
    funFact: "宫殿装饰大量使用对称、平移和旋转图形，是研究几何规律的漂亮例子。",
    scene: "palace",
  },
  {
    slug: "keukenhof-gardens",
    name: "库肯霍夫花园",
    city: "利瑟",
    country: "荷兰",
    tier: "WORLD",
    story: "春天的库肯霍夫花园开放数百万株郁金香、水仙与风信子，花带像彩色河流穿过草地和树林。园丁会提前设计开花时间与颜色组合。",
    explore: "跟着星宠比较花瓣形状和颜色渐变，寻找互补色，并观察蜜蜂怎样在花朵之间传粉。",
    funFact: "郁金香球根要在秋天种入土中，经过冬季低温后，春天才会发芽开花。",
    scene: "garden",
  },
  {
    slug: "neuschwanstein-castle",
    name: "新天鹅堡",
    city: "巴伐利亚",
    country: "德国",
    tier: "WORLD",
    story: "新天鹅堡建在阿尔卑斯山脚的岩丘上，白墙、尖塔与森林湖泊让它像童话城堡。内部房间用壁画讲述骑士、传说和音乐故事。",
    explore: "跟着星宠观察城堡为什么选在高处，数一数不同形状的塔顶，再画一座既漂亮又安全的城堡。",
    funFact: "城堡虽然看起来古老，却在十九世纪建造，当时已经计划使用电话等较新的技术。",
    scene: "palace",
  },
  {
    slug: "jungfrau-region",
    name: "瑞士少女峰",
    city: "伯尔尼高地",
    country: "瑞士",
    tier: "WORLD",
    story: "少女峰地区有雪山、冰川、绿色山谷和齿轨列车，短距离内就能看到不同海拔景观。列车沿陡坡向上，让人接近高山但也要注意低温与稀薄空气。",
    explore: "跟着星宠从山谷往上找草地、森林、裸岩和冰雪，比较它们出现的高度顺序。",
    funFact: "齿轨铁路在轨道中间增加带齿钢轨，列车齿轮咬住它，就能更安全地爬上陡坡。",
    scene: "mountain",
  },
  {
    slug: "schonbrunn-palace",
    name: "美泉宫",
    city: "维也纳",
    country: "奥地利",
    tier: "WORLD",
    story: "美泉宫是黄色外墙的大型宫殿，后方花园有整齐树篱、喷泉和通向高处的长轴。房间与花园讲述欧洲宫廷生活、音乐和园艺设计。",
    explore: "跟着星宠站在花园中轴线上寻找对称，比较修剪整齐的树篱与自然生长的树林有什么不同。",
    funFact: "莫扎特小时候曾在美泉宫演奏音乐，维也纳至今仍以丰富的古典音乐传统闻名。",
    scene: "palace",
  },
  {
    slug: "acropolis-athens",
    name: "雅典卫城",
    city: "雅典",
    country: "希腊",
    tier: "WORLD",
    story: "雅典卫城建在城市中央高地，帕特农神庙的石柱与三角屋顶成为古希腊建筑代表。站在山顶可以看见现代城市围绕古迹展开。",
    explore: "跟着星宠观察柱子并不是完全笔直，寻找建筑中的比例与重复，再想想怎样保护露天石质文物。",
    funFact: "帕特农神庙的柱子中部略微鼓起，这种细小调整能让远看时显得更挺拔自然。",
    scene: "temple",
  },
  {
    slug: "santorini-island",
    name: "圣托里尼岛",
    city: "爱琴海",
    country: "希腊",
    tier: "WORLD",
    story: "圣托里尼的白色房屋沿火山岛悬崖层层排列，蓝色圆顶、深蓝海水和黑色火山岩形成鲜明色彩。岛屿弯月形海湾来自古代火山活动。",
    explore: "跟着星宠观察房屋如何顺坡而建，比较白墙在阳光下的作用，并从地图上寻找火山口轮廓。",
    funFact: "白色墙面能反射强烈阳光，帮助房屋在炎热夏季保持相对凉爽。",
    scene: "island",
  },
  {
    slug: "prague-astronomical-clock",
    name: "布拉格天文钟",
    city: "布拉格",
    country: "捷克",
    tier: "WORLD",
    story: "布拉格老城天文钟有复杂表盘、星空符号和整点活动人偶，不只显示时间，也展示太阳、月亮在天空中的位置。周围彩色尖顶让广场像故事书。",
    explore: "跟着星宠辨认时针与天文盘，等待整点观察哪些小窗打开，再比较古代机械钟和电子钟。",
    funFact: "这座天文钟已经运行六百多年，内部许多齿轮必须精确配合，才能让不同显示同时移动。",
    scene: "tower",
  },
  {
    slug: "blue-lagoon-iceland",
    name: "冰岛蓝湖",
    city: "雷克雅内斯",
    country: "冰岛",
    tier: "WORLD",
    story: "蓝湖位于黑色火山岩之间，温暖乳蓝色水面冒着白色水汽。地下热水携带矿物来到地表，让寒冷环境里出现可以放松的温泉。",
    explore: "跟着星宠比较蓝水、黑岩和白雾三种颜色，想一想地球内部热量怎样把水加热。",
    funFact: "湖水含有二氧化硅等矿物，细小颗粒散射光线，使水看起来呈现特别的乳蓝色。",
    scene: "ice",
  },
  {
    slug: "norwegian-fjords",
    name: "挪威峡湾",
    city: "卑尔根地区",
    country: "挪威",
    tier: "WORLD",
    story: "挪威峡湾是海水深入陆地形成的狭长水道，两侧高山、瀑布和小村庄紧贴岸边。远古冰川像巨大的刻刀，把山谷磨得又深又陡。",
    explore: "跟着星宠从地图观察峡湾分叉，比较河谷与冰川谷形状，并寻找山坡上从雪水形成的瀑布。",
    funFact: "许多峡湾水深超过周围近海，因为冰川曾在陆地上挖出很深谷底，后来海水进入其中。",
    scene: "mountain",
  },
  {
    slug: "santa-claus-village",
    name: "圣诞老人村",
    city: "罗瓦涅米",
    country: "芬兰",
    tier: "WORLD",
    story: "圣诞老人村靠近北极圈，冬季积雪、驯鹿和长夜营造出童话气氛。邮局会收到世界各地孩子的信，北极圈标线也穿过园区。",
    explore: "跟着星宠在地图上找北极圈，比较极地冬夏白昼长度，再写一张感谢家人或朋友的小卡片。",
    funFact: "越靠近北极，冬季白昼越短、夏季越长；北极圈以北还会出现极夜和午夜太阳。",
    scene: "ice",
  },
  {
    slug: "lake-baikal",
    name: "贝加尔湖",
    city: "伊尔库茨克",
    country: "俄罗斯",
    tier: "WORLD",
    story: "贝加尔湖是世界上最深的淡水湖，四周有森林、山地和广阔冰面。冬季透明湖冰会出现长裂纹与蓝色气泡，夏季湖水清澈辽阔。",
    explore: "跟着星宠比较冰面不同蓝色，观察裂纹但不独自走上湖冰，并寻找只生活在这里的动物。",
    funFact: "贝加尔海豹是少见的淡水海豹，科学家仍在研究它们的祖先怎样来到这座内陆湖。",
    scene: "lake",
  },
  {
    slug: "cappadocia",
    name: "卡帕多奇亚",
    city: "格雷梅",
    country: "土耳其",
    tier: "WORLD",
    story: "卡帕多奇亚有被风雨雕成尖塔的火山岩、藏在岩石里的房间和清晨升空的热气球。柔软凝灰岩让古人能开凿住所、教堂与地下城。",
    explore: "跟着星宠观察岩柱为什么上粗下细，比较热气球升降与空气温度，并从高处寻找弯曲山谷。",
    funFact: "热气球里的空气被加热后密度变小，整个气球获得浮力，就能慢慢升向天空。",
    scene: "desert",
  },
  {
    slug: "burj-khalifa",
    name: "哈利法塔",
    city: "迪拜",
    country: "阿联酋",
    tier: "WORLD",
    story: "哈利法塔从沙漠城市中升起，层层收窄的银色塔身帮助它应对高空强风。观景层能看到密集道路、人工湖与远处沙漠海岸。",
    explore: "跟着星宠观察塔身由下到上怎样变细，想一想电梯要多快才能到高层，并寻找建筑平面里的花瓣形。",
    funFact: "塔的设计灵感之一来自沙漠花朵，Y形结构能增加稳定性，也让更多房间靠近窗户。",
    scene: "tower",
  },
  {
    slug: "petra-jordan",
    name: "佩特拉古城",
    city: "马安",
    country: "约旦",
    tier: "WORLD",
    story: "佩特拉隐藏在红色砂岩峡谷中，著名的卡兹尼神殿直接从整面岩壁雕出。古城还设计水渠和蓄水池，在干旱环境里收集珍贵雨水。",
    explore: "跟着星宠观察砂岩颜色条纹，寻找人工雕刻与自然岩壁的分界，再沿水渠想象雨水流向。",
    funFact: "佩特拉曾是商队贸易中心，香料和货物从不同地区来到这里，水利系统支持了城市生活。",
    scene: "desert",
  },
  {
    slug: "taj-mahal",
    name: "泰姬陵",
    city: "阿格拉",
    country: "印度",
    tier: "WORLD",
    story: "泰姬陵由白色大理石建成，中央圆顶、四座尖塔、水池与花园保持严格对称。清晨、正午和月光下，大理石会反射不同颜色。",
    explore: "跟着星宠在中轴线上寻找左右对应物体，观察水池倒影，再设计一个只用两种形状的对称花纹。",
    funFact: "墙面装饰使用宝石与彩石镶嵌，把花朵和文字嵌入大理石中，摸上去仍很平整。",
    scene: "palace",
  },
  {
    slug: "everest-view-nepal",
    name: "珠穆朗玛峰观景地",
    city: "萨加玛塔",
    country: "尼泊尔",
    tier: "WORLD",
    story: "从尼泊尔喜马拉雅山区可以遥望珠穆朗玛峰，雪山、冰川谷和高山村落分布在不同海拔。空气越高越稀薄，旅行者需要缓慢适应。",
    explore: "跟着星宠从山脚到峰顶寻找植物减少的顺序，比较云层和山峰高度，并学习高山安全知识。",
    funFact: "珠穆朗玛峰仍会因地壳运动以非常缓慢的速度变化，科学家不断用测量技术更新它的高度。",
    scene: "mountain",
  },
  {
    slug: "sigiriya-rock",
    name: "狮子岩",
    city: "中央省",
    country: "斯里兰卡",
    tier: "WORLD",
    story: "狮子岩是一块从平原突然升起的巨大岩石，古代宫殿、花园和蓄水池建在岩顶与周围。攀登路线会经过壁画、镜墙和巨大的狮爪遗迹。",
    explore: "跟着星宠从远处观察岩石轮廓，想一想怎样把水送上高处，再寻找花园中对称水池。",
    funFact: "古代花园拥有精巧喷泉和地下水道，雨季储存的水可以利用压力从石孔喷出。",
    scene: "mountain",
  },
  {
    slug: "gardens-by-the-bay",
    name: "滨海湾花园",
    city: "新加坡",
    country: "新加坡",
    tier: "WORLD",
    story: "滨海湾花园把巨大温室、空中步道和像树一样的垂直花园放进现代城市。不同温室控制温度与湿度，让热带地区也能展示凉爽气候植物。",
    explore: "跟着星宠观察超级树怎样收集太阳能和雨水，比较室内外气候，并寻找植物在立面上生长的方法。",
    funFact: "部分超级树安装太阳能板，也承担通风和收集雨水等工作，不只是夜间发光装饰。",
    scene: "garden",
  },
  {
    slug: "petronas-towers",
    name: "双子塔",
    city: "吉隆坡",
    country: "马来西亚",
    tier: "WORLD",
    story: "两座银色高楼以空中天桥相连，重复的几何楼层向天空逐渐收尖。建筑平面借鉴伊斯兰艺术中的八角星图案，现代材料与传统纹样结合。",
    explore: "跟着星宠找出两塔相同与不同部分，观察天桥位置，并用两个正方形旋转叠出八角星。",
    funFact: "连接双塔的天桥并没有完全固定死，而是允许轻微移动，以适应高楼随风摆动。",
    scene: "tower",
  },
  {
    slug: "grand-palace-bangkok",
    name: "曼谷大皇宫",
    city: "曼谷",
    country: "泰国",
    tier: "WORLD",
    story: "曼谷大皇宫有金色尖顶、彩色马赛克和层层院墙，阳光下细小装饰会闪闪发亮。建筑群展示泰国传统屋顶、神话形象与王室历史。",
    explore: "跟着星宠观察屋顶尖角和守门雕像，寻找重复彩色小片怎样拼成大图案，并尊重参观礼仪。",
    funFact: "许多墙面装饰由细小玻璃和彩瓷拼贴而成，近看像马赛克，远看则形成完整花纹。",
    scene: "palace",
  },
  {
    slug: "angkor-wat",
    name: "吴哥窟",
    city: "暹粒",
    country: "柬埔寨",
    tier: "WORLD",
    story: "吴哥窟由护城河、长廊和层层升高的塔组成，石壁浮雕讲述神话、战争和日常生活。附近一些遗迹被树根环抱，展示自然与建筑的漫长相遇。",
    explore: "跟着星宠观察塔群对称和浮雕故事顺序，比较树根与石墙力量，并学习不触摸脆弱雕刻。",
    funFact: "吴哥地区拥有复杂水库和水渠网络，古人用它们管理季节雨水并支持大城市生活。",
    scene: "temple",
  },
  {
    slug: "ha-long-bay",
    name: "下龙湾",
    city: "广宁",
    country: "越南",
    tier: "WORLD",
    story: "下龙湾海面上分布上千座石灰岩岛峰，绿色植物覆盖陡峭岩壁，船只在岛屿间穿行。海水侵蚀还形成洞穴、拱门和隐藏潟湖。",
    explore: "跟着星宠从远近观察岛峰大小，寻找像动物的轮廓，并比较海蚀洞与普通山洞。",
    funFact: "“下龙”意为龙降落的地方，传说龙吐出的宝石变成岛屿，帮助守护海湾。",
    scene: "ocean",
  },
  {
    slug: "mount-fuji",
    name: "富士山",
    city: "山梨与静冈",
    country: "日本",
    tier: "WORLD",
    story: "富士山是轮廓接近对称的火山，冬春季山顶常覆盖白雪，周围有湖泊、森林和城镇。天气晴朗时，倒影会在平静湖面形成“逆富士”。",
    explore: "跟着星宠寻找火山锥的对称轴，观察雪线随季节变化，并比较真实山峰和水中倒影。",
    funFact: "富士山由多次火山喷发逐渐堆叠形成，今天仍是一座被持续监测的活火山。",
    scene: "mountain",
  },
  {
    slug: "fushimi-inari-shrine",
    name: "伏见稻荷大社",
    city: "京都",
    country: "日本",
    tier: "WORLD",
    story: "成千上万座朱红色鸟居沿山路连续排列，形成像隧道一样的光影空间。石狐狸、森林和小型神社分布在步道旁。",
    explore: "跟着星宠观察鸟居重复带来的远近变化，数一小段柱子间距，并寻找狐狸雕像携带的不同物品。",
    funFact: "许多鸟居由个人或商家捐建，背面写着捐建者和日期，因此大小、新旧并不完全相同。",
    scene: "temple",
  },
  {
    slug: "gyeongbokgung-palace",
    name: "景福宫",
    city: "首尔",
    country: "韩国",
    tier: "WORLD",
    story: "景福宫背靠山峰，宫门、殿堂、池塘和长廊沿中轴展开。彩绘木构使用绿、红、蓝等颜色，屋檐曲线与远山相互呼应。",
    explore: "跟着星宠寻找左右对称的院落，比较彩绘纹样，并观察守门仪式里的服装、队形和节奏。",
    funFact: "传统建筑彩绘叫“丹青”，既有装饰作用，也能帮助保护木材免受风雨和虫害。",
    scene: "palace",
  },
  {
    slug: "gobi-desert-mongolia",
    name: "蒙古戈壁",
    city: "南戈壁",
    country: "蒙古",
    tier: "WORLD",
    story: "戈壁不全是沙丘，也有砾石平原、岩壁和稀疏草地，昼夜温差很大。双峰骆驼、野生动物与牧民生活都适应了干燥多风环境。",
    explore: "跟着星宠比较沙漠和戈壁地面，观察骆驼驼峰、脚掌怎样适应旅行，并准备节约水的办法。",
    funFact: "双峰骆驼驼峰储存的是脂肪而不是水，脂肪能在食物不足时提供能量。",
    scene: "desert",
  },
  {
    slug: "hobbiton-movie-set",
    name: "霍比屯",
    city: "玛塔玛塔",
    country: "新西兰",
    tier: "WORLD",
    story: "霍比屯坐落在绿色牧场丘陵中，圆门小屋、花园、石桥和水磨坊像童话村庄。它原本是电影布景，后来被保存为可以参观的故事世界。",
    explore: "跟着星宠观察圆门与普通门的不同，寻找布景如何隐藏现代设施，再设计一个住在山坡里的小家。",
    funFact: "为了让树看起来符合电影故事，工作人员曾给道具树一片片安装人工树叶。",
    scene: "grassland",
  },
  {
    slug: "great-barrier-reef",
    name: "大堡礁",
    city: "昆士兰",
    country: "澳大利亚",
    tier: "WORLD",
    story: "大堡礁由大量珊瑚礁、岛屿和浅海组成，是鱼类、海龟和许多微小生物的家。珊瑚看似石头，其实由许多小珊瑚虫共同建造。",
    explore: "跟着星宠比较不同珊瑚形状和鱼的颜色，想一想为什么不能触碰珊瑚，并寻找食物链线索。",
    funFact: "珊瑚体内生活着微小藻类，藻类提供能量和颜色；水温过高时它们离开，就会发生白化。",
    scene: "ocean",
  },
  {
    slug: "uluru",
    name: "乌鲁鲁",
    city: "北领地",
    country: "澳大利亚",
    tier: "WORLD",
    story: "乌鲁鲁是一块从澳大利亚中部平原升起的巨大红色岩体，日出日落时颜色会从橙红变成深紫。它对原住民阿南古人具有重要文化意义。",
    explore: "跟着星宠沿指定步道观察岩壁纹理和水痕，比较一天中光线颜色，并尊重不攀爬的当地约定。",
    funFact: "乌鲁鲁露在地面的部分只是巨大岩层的一部分，更多岩石继续延伸到地下。",
    scene: "desert",
  },
  {
    slug: "cape-of-good-hope",
    name: "好望角",
    city: "开普敦",
    country: "南非",
    tier: "WORLD",
    story: "好望角位于开普半岛南端附近，陡峭海岸、强风和开阔海面塑造出壮观景色。周围生长独特灌木，也生活着狒狒、鸵鸟等动物。",
    explore: "跟着星宠观察风把植物吹成什么方向，在地图上寻找绕过非洲南端的航线，并远离野生动物。",
    funFact: "好望角并不是非洲最南端，真正最南点是更向东南的厄加勒斯角。",
    scene: "ocean",
  },
  {
    slug: "maasai-mara",
    name: "马赛马拉草原",
    city: "纳罗克",
    country: "肯尼亚",
    tier: "WORLD",
    story: "马赛马拉有广阔稀树草原，角马、斑马、长颈鹿和狮子在这里寻找食物与水。季节变化会推动大群动物跨越河流与边界迁徙。",
    explore: "跟着星宠观察食草动物和食肉动物的身体特点，画一条迁徙路线，并理解不能下车靠近野生动物。",
    funFact: "角马大迁徙没有固定起点终点，动物会跟随降雨和新鲜草场进行一年一度的循环移动。",
    scene: "wildlife",
  },
  {
    slug: "mount-kilimanjaro",
    name: "乞力马扎罗山",
    city: "乞力马扎罗区",
    country: "坦桑尼亚",
    tier: "WORLD",
    story: "乞力马扎罗山从热带平原升到冰雪山顶，短距离内穿过农田、雨林、荒原和高山冰川。它是一座由多座火山锥组成的巨大山体。",
    explore: "跟着星宠把不同海拔景观按顺序排列，比较温度和植物变化，并在地图上找到赤道附近的雪山。",
    funFact: "虽然靠近赤道，山顶因为海拔接近六千米仍十分寒冷，但冰川正因气候变化不断缩小。",
    scene: "mountain",
  },
  {
    slug: "antarctic-peninsula",
    name: "南极半岛",
    city: "南极洲",
    country: "南极洲",
    tier: "WORLD",
    story: "南极半岛覆盖冰川、雪原和漂浮海冰，企鹅、海豹与鲸在寒冷海洋中生活。夏季白昼很长，科学家会在研究站观察气候、冰层和生物。",
    explore: "跟着星宠比较企鹅、海豹保暖方式，在地球仪上找到南极，并学习旅行者必须把垃圾全部带走。",
    funFact: "南极洲没有常住居民，来自许多国家的科学家轮流工作，并按照国际约定共同保护这里。",
    scene: "ice",
  },
];

const ALL_EXPANDED_DRAFTS = [
  ...nearbyDestinations,
  ...chinaDestinations,
  ...worldDestinations,
];

const EXPANDED_DESTINATION_ASSET_VERSION = "20260811";

export const EXPANDED_PET_DESTINATIONS = ALL_EXPANDED_DRAFTS.map((destination, index) => ({
  id: `pet-dest-expanded-${destination.slug}`,
  slug: destination.slug,
  name: destination.name,
  city: destination.city,
  country: destination.country,
  tier: destination.tier,
  introduction: `${destination.story}${destination.explore}`,
  funFact: destination.funFact,
  imageUrl: `/pet-assets/v1/destinations/expanded/${destination.slug}.webp?v=${EXPANDED_DESTINATION_ASSET_VERSION}`,
  sortOrder: 1_000 + index * 10,
  isEnabled: true,
  scene: destination.scene,
}));

export const LEGACY_DESTINATION_EXPLORATION_PROMPTS: Record<string, string> = {
  "chengdu-panda-base": "参观时可以观察大熊猫怎样握住竹子、怎样选择嫩叶，再比较它爬树和在地面行走的动作有什么不同。",
  dujiangyan: "跟着星宠站在观景处寻找鱼嘴、飞沙堰和宝瓶口，看看三部分怎样合作，把奔跑的江水送向不同方向。",
  "forbidden-city": "可以沿着中轴线寻找左右对称的宫殿，观察屋顶上动物装饰的数量，再想想不同院落分别承担什么任务。",
  "great-wall": "跟着星宠比较城墙、关口和烽火台的位置，想象没有电话的年代，人们怎样把消息快速传过一座座山。",
  "terracotta-warriors": "可以从发型、衣甲和姿势辨认不同陶俑，寻找两张不完全一样的脸，并学习只用眼睛保护文物。",
  "west-lake": "跟着星宠沿湖寻找桥、塔、堤和倒影，比较晴天与雨天的颜色，再把最喜欢的一处风景说成一句小诗。",
  huangshan: "可以观察迎客松怎样扎根岩缝，寻找像动物的奇石，并比较云海出现前后山峰远近感有什么变化。",
  "potala-palace": "跟着星宠观察建筑如何顺着山坡层层升高，比较红宫与白宫的颜色，并留意高原旅行需要慢慢行走。",
  "leaning-tower-pisa": "可以站在不同方向观察塔的倾斜，寻找每层重复的拱门，再想一想工程师怎样监测并保护这座斜塔。",
  "eiffel-tower": "跟着星宠寻找三角形钢架和交叉结构，比较塔底与塔顶宽度，再观察远处城市为什么看起来像一张地图。",
  "giza-pyramids": "可以比较三座主要金字塔的大小，观察石块层层排列的方式，并想象古人怎样组织运输与建造。",
  "sydney-opera-house": "跟着星宠从海港不同角度观察屋顶像帆、贝壳还是橘子瓣，再寻找建筑与海面倒影的关系。",
  "chengdu-museum": "可以挑一件古代生活用品，先猜用途再看说明，把它与今天家里的同类物品进行一次小小对比。",
  "jinsha-site-museum": "跟着星宠观察太阳神鸟的旋转图案，寻找金、玉和陶三种不同材料，并看看考古现场如何保护地下遗迹。",
  "du-fu-thatched-cottage": "可以在竹林、溪水和茅屋间寻找杜甫诗里的景物，听一首熟悉诗歌，再画出自己想象的春雨成都。",
  "wuhou-shrine": "跟着星宠辨认诸葛亮与三国人物的故事，观察红墙竹影和古柏，并说说智慧、勇气与合作分别是什么。",
  "kuanzhai-alley": "可以比较宽巷子和窄巷子的道路尺度，寻找木门、青砖与院落，再观察老街今天怎样继续被使用。",
  "mount-qingcheng": "跟着星宠听鸟叫和溪水判断方向，比较向阳与背阴处的植物，并在山路上寻找层层展开的古建筑。",
  "sanxingdui-museum": "可以观察青铜面具、神树和人像的夸张比例，猜一猜古蜀人的想象，再从展签寻找考古证据。",
  "leshan-giant-buddha": "跟着星宠从脚、手到头部感受巨大比例，寻找隐藏排水结构，并观察三条江在山脚怎样汇合。",
  "mount-emei": "可以把山脚、森林、云海和金顶按高度排列，比较温度与植物变化，并保持距离观察野生动物。",
  "zigong-dinosaur-museum": "跟着星宠从牙齿、脚爪和骨架姿势推测恐龙怎样生活，再看看化石埋藏现场如何为科学家保留线索。",
  jiuzhaigou: "可以比较不同海子的蓝绿颜色，观察倒木、瀑布和森林倒影，并理解不触碰水体是保护清澈环境的一部分。",
  "huanglong-valley": "跟着星宠观察彩池一层层降低的形状，比较水深与颜色变化，再想象矿物沉积需要多么漫长的时间。",
  "xiling-snow-mountain": "可以从索道上观察树林变小、气温降低的过程，寻找雪的不同形态，并学习高山保暖与安全规则。",
  "luodai-ancient-town": "跟着星宠寻找不同会馆的屋脊和门墙装饰，比较客家文化与成都生活相遇后留下的建筑线索。",
  "anren-ancient-town": "可以观察公馆、老街和复古小火车，挑一件老物品猜用途，再比较一百年前与今天的日常生活。",
  "pingle-ancient-town": "跟着星宠沿白沫江观察石桥和木屋，数一数桥孔，并想想居民为什么喜欢把房屋建在水边。",
  "sichuan-science-museum": "可以先对一个互动装置作出猜想，再亲手验证，把不同结果当成继续提问和发现新知识的起点。",
  "chengdu-natural-history-museum": "跟着星宠从矿物、恐龙到今天的动物一路观察，选择一件标本，用外形线索推测它来自怎样的环境。",
  "longquan-danjing-platform": "可以沿盘旋步道观察城市、山坡和远山的层次，比较近处与远处颜色，再寻找春季桃花的变化。",
  "yading-nature-reserve": "跟着星宠把雪山、森林、草甸和湖泊按海拔排列，慢慢行走适应高原，并坚持不踩踏脆弱植物。",
};

export const LEGACY_POSTCARD_CLOSING = "参观结束后，可以把最喜欢的一个细节画进旅行日记，再和家人说说它为什么让你记得最清楚。";
