import type { MathQuestionTypeDefinition } from "./types.js";

function defineQuestionType(
  definition: Omit<MathQuestionTypeDefinition, "previewFixtureId">,
): MathQuestionTypeDefinition {
  return {
    ...definition,
    previewFixtureId: `${definition.id}.default`,
  };
}

export const MATH_QUESTION_TYPES = [
  defineQuestionType({
    id: "N01",
    slug: "count-single-set",
    name: "单集合数物写数",
    domain: "N",
    coreGeneratorId: "COUNT_SINGLE_SET",
    description: "数出一组物体并写出数量。",
    responseModes: ["R01"],
    sceneStrategy: "SPRITE_COMPOSITION",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [18],
  }),
  defineQuestionType({
    id: "N02",
    slug: "count-grouped-containers",
    name: "分组或容器内计数",
    domain: "N",
    coreGeneratorId: "COUNT_GROUPED_CONTAINERS",
    description: "按第几组或第几个容器，数出里面的物体数量。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [15],
  }),
  defineQuestionType({
    id: "N03",
    slug: "count-structured",
    name: "结构化快速计数",
    domain: "N",
    coreGeneratorId: "COUNT_STRUCTURED",
    description: "利用行列、五个一组或十个一组的结构计数。",
    responseModes: ["R01"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [11, 15, 18],
  }),
  defineQuestionType({
    id: "N04",
    slug: "ordinal-left-right",
    name: "第几与左右序数",
    domain: "N",
    coreGeneratorId: "ORDINAL_LEFT_RIGHT",
    description: "从左边或右边数出目标对象排第几。",
    responseModes: ["R01", "R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 2],
    sourceImageNumbers: [13, 15],
  }),
  defineQuestionType({
    id: "N05",
    slug: "position-before-after",
    name: "前面、后面与相邻位置数量",
    domain: "N",
    coreGeneratorId: "POSITION_BEFORE_AFTER",
    description: "根据队列方向判断目标前后各有几个对象。",
    responseModes: ["R01", "R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 2],
    sourceImageNumbers: [13],
  }),
  defineQuestionType({
    id: "N06",
    slug: "adjacent-numbers",
    name: "相邻数",
    domain: "N",
    coreGeneratorId: "ADJACENT_NUMBERS",
    description: "完成三格或五格相邻数，包含 20 以内顺数、倒数和间隔数列。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [18, 19],
  }),
  defineQuestionType({
    id: "N07",
    slug: "number-sequence",
    name: "数列找规律填数",
    domain: "N",
    coreGeneratorId: "NUMBER_SEQUENCE",
    description: "在顺数、倒数或等间隔数列中填写缺失数字。",
    responseModes: ["R02"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [18],
  }),
  defineQuestionType({
    id: "N08",
    slug: "compare-numbers",
    name: "两数大小比较",
    domain: "N",
    coreGeneratorId: "COMPARE_NUMBERS",
    description: "在两个数之间填写大于、小于或等于号。",
    responseModes: ["R03"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [18, 19, 23],
  }),
  defineQuestionType({
    id: "N09",
    slug: "order-numbers",
    name: "多个数排序",
    domain: "N",
    coreGeneratorId: "ORDER_NUMBERS",
    description: "把多个数字按从小到大或从大到小排列。",
    responseModes: ["R08"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [15],
  }),
  defineQuestionType({
    id: "N10",
    slug: "compare-quantities",
    name: "数量多少及相差多少",
    domain: "N",
    coreGeneratorId: "COMPARE_QUANTITIES",
    description: "比较两组或多组物体的多少、最多最少或相差数量。",
    responseModes: ["R01", "R05"],
    sceneStrategy: "SPRITE_COMPOSITION",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [23, 24],
  }),
  defineQuestionType({
    id: "N11",
    slug: "compare-attributes",
    name: "比较物体大小",
    domain: "N",
    coreGeneratorId: "COMPARE_ATTRIBUTES",
    description: "在保持物体造型一致时，比较物体本身的大小。",
    responseModes: ["R05", "R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [1, 2],
    sourceImageNumbers: [23, 24],
  }),
  defineQuestionType({
    id: "N12",
    slug: "compare-height",
    name: "比较物体高矮",
    domain: "N",
    coreGeneratorId: "COMPARE_HEIGHT",
    description: "在统一基线下比较物体的高矮。",
    responseModes: ["R05", "R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [1, 2],
    sourceImageNumbers: [23, 24],
  }),
  defineQuestionType({
    id: "N13",
    slug: "compare-length",
    name: "比较物体长短",
    domain: "N",
    coreGeneratorId: "COMPARE_LENGTH",
    description: "比较不同尺子、丝带、画笔等物体的长短。",
    responseModes: ["R05", "R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [1, 2],
    sourceImageNumbers: [23, 24],
  }),
  defineQuestionType({
    id: "N14",
    slug: "compare-weight",
    name: "比较物体轻重",
    domain: "N",
    coreGeneratorId: "COMPARE_WEIGHT",
    description: "根据跷跷板或天平的高低判断物体轻重。",
    responseModes: ["R05"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [1, 2],
    sourceImageNumbers: [23, 24],
  }),
  defineQuestionType({
    id: "N15",
    slug: "select-ordered-range",
    name: "按方向圈选指定对象",
    domain: "N",
    coreGeneratorId: "SELECT_ORDERED_RANGE",
    description: "从左边或右边起，圈出指定数量的连续对象。",
    responseModes: ["R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 2],
    sourceImageNumbers: [13, 15],
  }),
  defineQuestionType({
    id: "N16",
    slug: "construct-quantity",
    name: "按要求补画数量",
    domain: "N",
    coreGeneratorId: "CONSTRUCT_QUANTITY",
    description: "通过添加或删去物体，画出比给定数量多或少的数量。",
    responseModes: ["R07"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 2],
    sourceImageNumbers: [24],
  }),

  defineQuestionType({
    id: "P01",
    slug: "representation-read-write",
    name: "看图写数",
    domain: "P",
    coreGeneratorId: "REPRESENTATION_READ_WRITE",
    description: "数出十捆和单根小棍，把图片表示的数量写成数字。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_100",
    difficultyRange: [1, 2],
    sourceImageNumbers: [10, 11],
  }),
  defineQuestionType({
    id: "P03",
    slug: "place-value-decompose",
    name: "数的组成与数位意义",
    domain: "P",
    coreGeneratorId: "PLACE_VALUE_DECOMPOSE",
    description: "沿分支把两位数分解为几个十和几个一。",
    responseModes: ["R02"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_100",
    difficultyRange: [1, 3],
    sourceImageNumbers: [10, 11],
  }),
  defineQuestionType({
    id: "P05",
    slug: "abacus-read",
    name: "看计数器或珠算图写数",
    domain: "P",
    coreGeneratorId: "ABACUS_READ",
    description: "根据十位杆和个位杆上的珠子写出数字。",
    responseModes: ["R01"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [10, 11, 17, 18, 19],
  }),
  defineQuestionType({
    id: "P06",
    slug: "abacus-build",
    name: "画珠或用固定珠数表示不同数",
    domain: "P",
    coreGeneratorId: "ABACUS_BUILD",
    description: "把数字表示成珠子，或枚举固定珠数在不同数位上的分配。",
    responseModes: ["R02", "R06"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [10, 11],
  }),
  defineQuestionType({
    id: "P07",
    slug: "place-value-reasoning",
    name: "数位条件推理与加一",
    domain: "P",
    coreGeneratorId: "PLACE_VALUE_REASONING",
    description: "根据数位条件确定数字，或判断计数器添一颗珠子后的可能结果。",
    responseModes: ["R01", "R05"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_100",
    difficultyRange: [2, 3],
    sourceImageNumbers: [10, 11],
  }),

  defineQuestionType({
    id: "C02",
    slug: "chain-addition",
    name: "连加",
    domain: "C",
    coreGeneratorId: "CHAIN_ADDITION",
    description: "连续计算三个或更多加数的和。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [1, 16],
  }),
  defineQuestionType({
    id: "C03",
    slug: "chain-subtraction",
    name: "连减",
    domain: "C",
    coreGeneratorId: "CHAIN_SUBTRACTION",
    description: "从一个数连续减去两个或更多数。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [1],
  }),
  defineQuestionType({
    id: "C04",
    slug: "fill-operator",
    name: "在等式中填加号或减号",
    domain: "C",
    coreGeneratorId: "FILL_OPERATOR",
    description: "根据等式结果选择加号或减号。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [21, 22],
  }),
  defineQuestionType({
    id: "C05",
    slug: "number-bond",
    name: "数的分与合",
    domain: "C",
    coreGeneratorId: "NUMBER_BOND",
    description: "根据整体和两个部分填写分合树中的未知数。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [15, 19],
  }),
  defineQuestionType({
    id: "C06",
    slug: "missing-number-equation",
    name: "算式缺数",
    domain: "C",
    coreGeneratorId: "MISSING_NUMBER_EQUATION",
    description: "填写未知加数、未知和、未知被减数、未知减数或未知差。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [10, 19],
  }),
  defineQuestionType({
    id: "C07",
    slug: "within-10-no-carry-borrow",
    name: "10以内不进位不退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "10以内加减法，不出现进位或退位。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 2],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C08",
    slug: "within-20-no-carry-borrow",
    name: "20以内不进位不退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "20以内加减法，不出现进位或退位。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C09",
    slug: "within-50-no-carry-borrow",
    name: "50以内不进位不退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "50以内加减法，不出现进位或退位。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_100",
    difficultyRange: [2, 3],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C10",
    slug: "within-100-no-carry-borrow",
    name: "100以内不进位不退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "100以内加减法，不出现进位或退位。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_100",
    difficultyRange: [2, 3],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C11",
    slug: "within-10-carry-borrow",
    name: "10以内进位退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "10以内重点练习凑十进位和借位减法。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_10",
    difficultyRange: [2, 3],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C12",
    slug: "within-20-carry-borrow",
    name: "20以内进位退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "20以内重点练习进位加法和退位减法。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C13",
    slug: "within-50-carry-borrow",
    name: "50以内进位退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "50以内重点练习进位加法和退位减法。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_100",
    difficultyRange: [2, 3],
    sourceImageNumbers: [1, 19],
  }),
  defineQuestionType({
    id: "C14",
    slug: "within-100-carry-borrow",
    name: "100以内进位退位加减",
    domain: "C",
    coreGeneratorId: "BOUNDED_ARITHMETIC",
    description: "100以内重点练习进位加法和退位减法。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_100",
    difficultyRange: [2, 3],
    sourceImageNumbers: [1, 19],
  }),

  defineQuestionType({
    id: "V01",
    slug: "picture-parts-find-total",
    name: "两部分看图求总数",
    domain: "V",
    coreGeneratorId: "PART_WHOLE_TOTAL",
    description: "根据两组物体列出加法算式求总数。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [6, 7],
  }),
  defineQuestionType({
    id: "V02",
    slug: "picture-total-find-part",
    name: "看图已知总数和一部分求另一部分",
    domain: "V",
    coreGeneratorId: "PART_WHOLE_MISSING",
    description: "根据总数、已知部分和问号位置列出减法算式。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [6, 7],
  }),
  defineQuestionType({
    id: "V03",
    slug: "picture-chain-addition",
    name: "三组或多组看图连加",
    domain: "V",
    coreGeneratorId: "VISUAL_CHAIN_ADDITION",
    description: "把三组或更多可见分组写成连加算式。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [6, 7, 16],
  }),
  defineQuestionType({
    id: "V04",
    slug: "picture-cross-out",
    name: "划去一部分求剩余",
    domain: "V",
    coreGeneratorId: "TAKE_AWAY_REMAINING",
    description: "根据图片中被划去的一组物体列出一步减法。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [6, 7],
  }),
  defineQuestionType({
    id: "V05",
    slug: "picture-chain-subtraction",
    name: "分两次划去的连减",
    domain: "V",
    coreGeneratorId: "VISUAL_CHAIN_SUBTRACTION",
    description: "根据两批不同删除标记列出连减算式。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [6, 7],
  }),
  defineQuestionType({
    id: "V06",
    slug: "bar-bracket-model",
    name: "括号图或线段式部分整体模型",
    domain: "V",
    coreGeneratorId: "BAR_BRACKET_MODEL",
    description: "根据总括号、分段括号和问号位置判断整体或部分。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [6, 7],
  }),
  defineQuestionType({
    id: "V07",
    slug: "fact-family-four",
    name: "一图四式",
    domain: "V",
    coreGeneratorId: "FACT_FAMILY_FOUR",
    description: "根据两个部分和整体写两道加法与两道减法算式。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_10",
    difficultyRange: [2, 3],
    sourceImageNumbers: [25, 26],
  }),

  defineQuestionType({
    id: "W01",
    slug: "word-combine-total",
    name: "合并型应用题",
    domain: "W",
    coreGeneratorId: "PART_WHOLE_TOTAL",
    description: "两个部分合起来，求一共有多少。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [2, 3, 4, 5, 20],
  }),
  defineQuestionType({
    id: "W02",
    slug: "word-add-to-result",
    name: "增加型应用题",
    domain: "W",
    coreGeneratorId: "PART_WHOLE_TOTAL",
    description: "原来有一些，又增加一些，求现在有多少。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [3, 4, 20],
  }),
  defineQuestionType({
    id: "W03",
    slug: "word-take-away-result",
    name: "减少型应用题",
    domain: "W",
    coreGeneratorId: "TAKE_AWAY_REMAINING",
    description: "原来有一些，减少一些，求还剩多少。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [3, 4, 5, 20],
  }),
  defineQuestionType({
    id: "W04",
    slug: "word-change-unknown",
    name: "变化量未知应用题",
    domain: "W",
    coreGeneratorId: "PART_WHOLE_MISSING",
    description: "已知原来和现在，求又来、拿走或第二次使用的数量。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [3, 4],
  }),
  defineQuestionType({
    id: "W05",
    slug: "word-part-unknown",
    name: "部分未知应用题",
    domain: "W",
    coreGeneratorId: "PART_WHOLE_MISSING",
    description: "已知总量和其中一类的数量，求另一类的数量。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 2],
    sourceImageNumbers: [4],
  }),
  defineQuestionType({
    id: "W06",
    slug: "word-compare-difference",
    name: "比较型相差数应用题",
    domain: "W",
    coreGeneratorId: "COMPARE_QUANTITIES",
    description: "比较两种数量，求一种比另一种多或少多少。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [5, 20],
  }),
  defineQuestionType({
    id: "W07",
    slug: "word-equal-groups-combine",
    name: "同样多与合并应用题",
    domain: "W",
    coreGeneratorId: "PART_WHOLE_TOTAL",
    description: "已知一组数量和另一组同样多，求两组一共多少。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [3],
  }),
  defineQuestionType({
    id: "W08",
    slug: "word-compare-quantity-unknown",
    name: "比较关系求未知数量",
    domain: "W",
    coreGeneratorId: "COMPARISON_UNKNOWN_AMOUNT",
    description: "已知一个数量和相差数，求较多量或较少量。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [5, 20],
  }),
  defineQuestionType({
    id: "W09",
    slug: "word-start-unknown",
    name: "原有数量未知应用题",
    domain: "W",
    coreGeneratorId: "START_UNKNOWN",
    description: "已知增加或减少的数量和最后结果，反求原来有多少。",
    responseModes: ["R04"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_20",
    difficultyRange: [2, 3],
    sourceImageNumbers: [3, 4, 20],
  }),

  defineQuestionType({
    id: "S01",
    slug: "spatial-one-dimension",
    name: "按序数反向找对象",
    domain: "S",
    coreGeneratorId: "SPATIAL_ONE_DIMENSION",
    description: "根据从左或从右的序数，找出对应的对象。",
    responseModes: ["R01", "R05", "R06"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 2],
    sourceImageNumbers: [13, 14],
  }),
  defineQuestionType({
    id: "S02",
    slug: "spatial-grid",
    name: "二维位置关系",
    domain: "S",
    coreGeneratorId: "SPATIAL_GRID",
    description: "判断座位图、货架或方格中的上、下、左、右关系。",
    responseModes: ["R01", "R05"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [1, 3],
    sourceImageNumbers: [14],
  }),
  defineQuestionType({
    id: "S03",
    slug: "logic-grid",
    name: "多条件逻辑表格",
    domain: "S",
    coreGeneratorId: "LOGIC_GRID",
    description: "根据肯定、否定、相同和互异条件完成匹配表格。",
    responseModes: ["R05"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [2, 3],
    sourceImageNumbers: [8],
  }),
  defineQuestionType({
    id: "S04",
    slug: "count-cubes",
    name: "数立体小正方体",
    domain: "S",
    coreGeneratorId: "COUNT_CUBES",
    description: "数出由单位正方体程序化搭建的立体中共有几个小正方体。",
    responseModes: ["R01"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_10",
    difficultyRange: [1, 3],
    sourceImageNumbers: [9, 12],
  }),
  defineQuestionType({
    id: "S05",
    slug: "spatial-relative-one-dimension",
    name: "一维相对方位",
    domain: "S",
    coreGeneratorId: "SPATIAL_RELATIVE_ONE_DIMENSION",
    description: "以一个对象为参照，判断另一对象在它的左边或右边。",
    responseModes: ["R05"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "NON_NUMERIC",
    difficultyRange: [1, 2],
    sourceImageNumbers: [13, 14],
  }),
] as const satisfies readonly MathQuestionTypeDefinition[];

/**
 * Merged teaching types stay out of the user-facing catalogue, but retain
 * lookup entries so saved parent settings and active task snapshots from
 * older releases continue to generate valid questions.
 */
export const MATH_LEGACY_QUESTION_TYPES = [
  defineQuestionType({
    id: "C01",
    slug: "one-step-arithmetic-legacy",
    name: "10或20以内一步加减（旧配置）",
    domain: "C",
    coreGeneratorId: "ONE_STEP_ARITHMETIC",
    description: "旧版一步加减配置，已拆分到按范围和进退位练习。",
    responseModes: ["R01"],
    sceneStrategy: "NONE",
    numberRange: "WITHIN_20",
    difficultyRange: [1, 3],
    sourceImageNumbers: [19],
  }),
  defineQuestionType({
    id: "P02",
    slug: "place-value-compose-legacy",
    name: "看图写数（旧配置）",
    domain: "P",
    coreGeneratorId: "PLACE_VALUE_COMPOSE",
    description: "旧版“几个十和几个一组成一个数”配置，已合并到 P01。",
    responseModes: ["R01", "R02"],
    sceneStrategy: "PROGRAMMATIC_AND_SPRITES",
    numberRange: "WITHIN_100",
    difficultyRange: [1, 2],
    sourceImageNumbers: [7, 10, 11],
  }),
  defineQuestionType({
    id: "P04",
    slug: "place-value-meaning-legacy",
    name: "数的组成与数位意义（旧配置）",
    domain: "P",
    coreGeneratorId: "PLACE_VALUE_MEANING",
    description: "旧版数位意义配置，已合并到 P03。",
    responseModes: ["R02"],
    sceneStrategy: "PROGRAMMATIC",
    numberRange: "WITHIN_100",
    difficultyRange: [1, 3],
    sourceImageNumbers: [10, 11],
  }),
] as const satisfies readonly MathQuestionTypeDefinition[];

export type MathQuestionTypeId =
  | (typeof MATH_QUESTION_TYPES)[number]["id"]
  | (typeof MATH_LEGACY_QUESTION_TYPES)[number]["id"];

export const MATH_QUESTION_TYPES_BY_ID = Object.fromEntries(
  [...MATH_QUESTION_TYPES, ...MATH_LEGACY_QUESTION_TYPES].map((definition) => [definition.id, definition]),
) as Record<MathQuestionTypeId, (typeof MATH_QUESTION_TYPES)[number]>;

export function getMathQuestionTypesByDomain(
  domain: MathQuestionTypeDefinition["domain"],
) {
  return MATH_QUESTION_TYPES.filter((definition) => definition.domain === domain);
}
